# Introduction

<p>In this session, you will learn about the high-level API Keras and how to <strong>implement a neural network using Keras</strong>. You will also explore some best practices for training neural networks, dropouts and batch normalisation.</p>

<h2 dir="ltr">In this Session</h2>

<p dir="ltr">We will cover the following topics:</p>

<ul><li dir="ltr" aria-level="1"><p dir="ltr" role="presentation">Keras: High-level API using TensorFlow</p></li><li dir="ltr" aria-level="1"><p dir="ltr" role="presentation">Implementation of neural networks using Keras</p></li><li dir="ltr" aria-level="1"><p dir="ltr" role="presentation">Epoch, batch, overfitting and underfitting</p></li><li dir="ltr" aria-level="1"><p dir="ltr" role="presentation">Dropouts and batch normalisation</p></li></ul>

<div class="MuiBox-root css-u715et-fullWidthWithAssetNameContainer"><div class="MuiBox-root css-qgb4hw"><div class="MuiBox-root css-1xzog2f" id="switch-player-content"></div><div class="MuiBox-root css-j7qwjs" data-testid="switch-player"><div class="MuiBox-root css-1bi8ut6"><div class="text_component" data-testid="text-component"><p dir="ltr">In this segment, you will learn how to build neural networks using Keras, a deep learning library that you will primarily be using throughout this course.&nbsp;</p><p>&nbsp;</p><p dir="ltr">Keras is a high-level library designed to work on top of Theano or TensorFlow. The main advantage of using Keras is that it is an<strong> easy-to-use, minimalistic API</strong> that can be used to build and deploy deep learning models quickly. Due to its simplicity, Keras's syntax and model building pipeline is easy to learn for beginners (although it does not compromise on flexibility, you can do almost everything with Keras that you do with pure TensorFlow or Theano).</p><p dir="ltr"><b id="docs-internal-guid-811ca30c-7fff-55ad-adea-1deb8edc4b5d">&nbsp;</b></p><p dir="ltr">You will be surprised to see how only a few lines of Python code in Keras can build and train complex, deep neural networks. In this segment, you will learn about the typical model-building process in Keras.</p><p dir="ltr">&nbsp;</p>

# Building neural networks in Keras

<p dir="ltr"><b id="docs-internal-guid-09426aaf-7fff-b157-0f88-856e95494f91">Download the notebook file attached below. It contains the code that will be used in this segment.</b></p></div></div><div class="MuiBox-root css-0"><div class="MuiBox-root css-1xdhyk6"><div class="MuiBox-root css-4yl6ul"><button class="MuiButtonBase-root MuiButton-root MuiButton-text MuiButton-textPrimary MuiButton-sizeMedium MuiButton-textSizeMedium MuiButton-root MuiButton-text MuiButton-textPrimary MuiButton-sizeMedium MuiButton-textSizeMedium css-188ece4" tabindex="0" type="button" data-testid="button"><span class="PrismButton-text">Download</span></button></div></div></div><div class="MuiBox-root css-1bi8ut6"><div class="text_component" data-testid="text-component"><p><b id="docs-internal-guid-4c87ecb9-7fff-947a-c802-b64d4ca8245a">Download the data set provided below.</b></p></div></div><div class="MuiBox-root css-0"></div></div><div class="MuiBox-root css-w2n25o" data-testid="player-footer"><button class="MuiButtonBase-root MuiButton-root MuiButton-text MuiButton-textPrimary MuiButton-sizeMedium MuiButton-textSizeMedium MuiButton-root MuiButton-text MuiButton-textPrimary MuiButton-sizeMedium MuiButton-textSizeMedium css-12r6e1j" tabindex="0" type="button" data-testid="button"><span class="PrismButton-text">Dataset</span></button></div></div></div>

## Keras Installation

<div class="text_component" data-testid="text-component"><p dir="ltr">To install Keras, open your Jupyter Notebook and implement the following command<b>:</b></p><p dir="ltr">&nbsp;</p><pre>!pip install keras
</pre><p>To check the version of Keras on your system, execute the following command (Note: Do not forget to import Keras.)</p><p>&nbsp;</p><pre>print(keras.__version__)
</pre><p dir="ltr">Note that you need to have either Theano or TensorFlow on your system in order to use Keras. So, you should install either of the two before importing Keras; otherwise, it might throw an error. So, you first need to install TensorFlow if not already done. For this, you can execute the following command:</p><pre>!pip install tensorflow
</pre><p>Keras by default uses TensorFlow as the backend. If you wish to use Keras with Theano as the backend, you need to find the 'keras.json' file and change "backend": "tensorflow" to "backend":"theano" in the .json file.</p><p>&nbsp;</p><p>Now that you know how to install Keras and TensorFlow, let's take a look at the steps implemented by Keras for building a model.</p><p>&nbsp;</p><p><strong>There are six main steps involved in building a model using Keras:</strong></p><p>&nbsp;</p><p dir="ltr" role="presentation"><b id="docs-internal-guid-641d0ad5-7fff-d825-b76a-cb6f204972f6">1. Load the data:</b></p><p dir="ltr" role="presentation">We load the data available using the following function as defined in the notebook:</p><pre>load_data()
</pre><p dir="ltr">Note that the shape of the matrices changes in the Keras implementation with respect to the Numpy implementation. The following lines of code take the transpose of each of the matrices read by load_data() function and assign the matrices to the corresponding variables:</p><pre>train_set_x = train_set_x.T
train_set_y = train_set_y.T
test_set_x = test_set_x.T
test_set_y = test_set_y.T
</pre><p>&nbsp;</p><p><b id="docs-internal-guid-015fa723-7fff-2bc3-5fb9-a1452cb0abe9">2. Define the model:</b></p><p dir="ltr">Typically, models in Keras are defined as a sequence of layers. So, we first need to create a model, 'nn_model', as follows:&nbsp;</p><pre>nn_model = Sequential()
</pre><p dir="ltr">This model has no layers as of now. We can add as many layers as we want to it. Let's add the first hidden layer. As we add a layer, we also need to specify the number of neurons in the layer and the activation function they will use. You will observe that we use the function 'Dense', which specifies that the layers are fully connected, i.e., every neuron in one layer will be connected to every other neuron in the next layer. The line of code added within the model is as follows:</p><pre>nn_model.add(Dense(35, input_dim=784, activation='relu'))
</pre><p>Here, as an example, ‘35’ denotes the number of neurons in the hidden layer and ‘784’ denotes the input size.</p><p dir="ltr">You can find more types of layers <a href="https://keras.io/api/layers/">here</a>.</p><p dir="ltr">&nbsp;</p><p dir="ltr" role="presentation"><b id="docs-internal-guid-3ebaf67a-7fff-4a31-bdb6-3c87430a433d">3. Compile the model:</b></p><p dir="ltr">After we have defined the model, we need to compile the model. During this step, Keras uses the backend libraries to efficiently represent the above-described model for training and prediction. We need to specify the loss function, the metrics as well as the optimiser in this step. In a classification problem, the loss function is the cross-entropy loss, which is 'categorical_crossentropy' in Keras. The metrics and the optimiser we use are 'accuracy' and 'adam' (consider this as an optimiser similar to gradient descent, which helps you to find optimum values of your model’s parameters). The line of code added in the model for compilation is as follows:&nbsp;<b>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</b></p><pre>nn_model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
</pre><p dir="ltr"><b id="docs-internal-guid-dc4f180d-7fff-ec32-710f-5e5bd45c8207">&nbsp;</b></p><p dir="ltr" role="presentation"><b id="docs-internal-guid-493578d8-7fff-615e-1c4b-9ec64075b740">4.&nbsp;</b><b>Fit the model:</b></p><p dir="ltr">The next step is to fit the model on the data set available. You need to pass the training data present in the variables 'train_set_x' and 'train_set_y' that you created earlier. You also need to pass the number of epochs you want for the training to happen. Essentially, 1 epoch is 1 pass through the entire data set in mini-batches (we will discuss this in the subsequent segments). So, you also need to specify the mini-batch size (the number of data points to be sent through the neural network in one go).</p><pre>nn_model.fit(train_set_x, train_set_y, epochs=10, batch_size=32)
</pre><p dir="ltr">Note that unless we call the 'model.fit()' function, the training does not begin.&nbsp;</p><p dir="ltr">&nbsp;</p><p dir="ltr" role="presentation"><b id="docs-internal-guid-65be88e7-7fff-7700-45a0-ed205c78b422">5. Evaluate the model:</b></p><p dir="ltr">In this step, we can see the accuracy scores that we finally achieved using the following command:</p><pre>scores_train = nn_model.evaluate(train_set_x, train_set_y)

print("\n%s: %.2f%%" % (nn_model.metrics_names[1], scores_train[1]*100))
</pre><p dir="ltr">To get the score on the test data, we can write the following code:</p><pre>scores_test = nn_model.evaluate(test_set_x, test_set_y)

print("\n%s: %.2f%%" % (nn_model.metrics_names[1], scores_test[1]*100))
</pre><p dir="ltr">Note that we only changed the data set from train to test.</p><p>&nbsp;</p><p dir="ltr" role="presentation"><b id="docs-internal-guid-54f1167d-7fff-8fa5-99b8-ebc4bc337c27">6. Make predictions:</b></p><p dir="ltr" role="presentation">Predictions can be performed using the '.predict()' function in the following manner:</p><pre>predictions = nn_model.predict(test_set_x)
</pre><p>&nbsp;</p><p dir="ltr"><strong>These are the steps involved in building a model in Keras</strong>. You must have observed that we need not write any code for feedforward or backpropagation as we did when we implemented the neural network using TensorFlow. Using Keras eliminates all those efforts. Keras is used almost everywhere because it is quite flexible. You may want to refer to the complete documentation of Keras <a href="https://keras.io/getting_started/">here</a>.</p><p dir="ltr">&nbsp;</p><p dir="ltr">Let’s proceed to the housing price prediction example for a demonstration on how to build and train a model. We will first perform data preprocessing of the housing data set before proceeding to model building using Keras.</p></div>

In [1]:
import pandas as pd
import numpy as np
import sklearn
import tensorflow as tf
from tensorflow import keras
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

In [2]:
# In case of errors, check if you are using the correct versions of the libraries. This notebook works on the following versions of libraries. Specify these versions if you get version related errors.
# TensorFlow version: 2.17.0
# Pandas version: 2.1.4
# NumPy version: 1.26.4
# Scikit-learn version: 1.5.2
# Keras version: 3.4.1

# print("TensorFlow version:", tf.__version__)
# print("Pandas version:", pd.__version__)
# print("NumPy version:", np.__version__)
# print("Scikit-learn version:", sklearn.__version__)
# print("Keras version:", tf.keras.__version__)

## Part 1: Import the Housing data and do feature transformations

In [8]:
df= pd.read_csv('4.2 house-price-full-1-.csv')
df.head()

   bedrooms  sqft_living    price
0         3         1340   313000
1         5         3650  2384000
2         3         1930   342000
3         3         2000   420000
4         4         1940   550000

In [9]:
X = df.copy()
# Remove target
Y = X.pop('price')

# perform a scaler transform of the input data
scaler = StandardScaler()
X = scaler.fit_transform(X)

# perform log transformation of target variable (For Sandeep: Is this needed?)
Y = np.log(Y)

In [10]:
df_scaled = pd.DataFrame(X)
df_scaled

            0         1
0   -0.433198 -0.753258
1    1.675735  1.457330
2   -0.433198 -0.188649
3   -0.433198 -0.121661
4    0.621269 -0.179079
..        ...       ...
494  0.621269  0.873582
495  1.675735  2.299459
496 -0.433198 -0.724549
497 -0.433198 -0.179079
498 -0.433198 -1.040347

[499 rows x 2 columns]

In [11]:
Y

0      12.653958
1      14.684290
2      12.742566
3      12.948010
4      13.217674
         ...
494    13.380102
495    13.764217
496    12.128111
497    12.721886
498    12.254863
Name: price, Length: 499, dtype: float64

## Part 2: Create Model Using `keras`

![](multiple_neurons.png)

In [12]:
from tensorflow import keras

In [14]:
# model = keras.Sequential(
#     [
#         keras.layers.Dense(
#             2, activation="sigmoid", input_shape=(X.shape[-1],)
#         ),
#         keras.layers.Dense(1, activation="linear")
#     ]
# )
# model.summary()

# Newer versions of Keras support this:
model = keras.Sequential()

# INPUT SIZE SAME AS THE TRAINING DATA X SHAPE
model.add(keras.layers.Input(shape=(X.shape[-1],)))
# define the hidden layer 
model.add(keras.layers.Dense(2, activation="sigmoid"))
# define the output layer
model.add(keras.layers.Dense(1, activation="linear"))
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                      │ (None, 2)                   │               6 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 1)                   │               3 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

Code above has take care of this part that we saw in the tensorflow implemetation

```python
def random_init_params():
    w1 = tf.Variable(tf.random.uniform((2, 2)))
    b1 = tf.Variable(tf.random.uniform((1, 2)))
    w2 = tf.Variable(tf.random.uniform((2, 1)))
    b2 = tf.Variable(tf.random.uniform((1, 1)))
    return w1,b1,w2,b2


def forward_prop(x, w1, b1, w2, b2):
    z1 = tf.matmul(x,w1) + b1
    h1 = tf.math.sigmoid(z1)
    z2 = tf.matmul(h1,w2) + b2
    h2 = z2
    return h2
```

## Part 3: Training Loop

In [16]:
model.compile(
    optimizer=keras.optimizers.SGD(), loss="mean_squared_error"
)

```python
def train(x, y, w1, b1, w2, b2):
    y_true = y
    with tf.GradientTape() as g:
        y_pred = forward_prop(x, w1, b1, w2, b2)

        # loss
        loss = 0.5*(y_true - y_pred)** 2
    
    #Gradient calculation  
    print("**************************************************")
    print("GRADIENTS")
    print("**************************************************")
    gw1, gb1, gw2, gb2 = g.gradient(loss, [w1, b1, w2, b2])
    print(" the gradient for 1st layer weights are:\n",gw1.numpy())
    print("--------------------------------------------------")
    print(" the gradient for 2nd layer weights are:\n",gw2.numpy())
    print("--------------------------------------------------")
    print(" the gradient for 1st layer bias are:\n",gb1.numpy())
    print("--------------------------------------------------")
    print(" the gradient for 2nd layer bias are:\n",gb2.numpy())
    print("--------------------------------------------------")

    # Gradient descent:
    lr=0.2
    w1.assign_sub(lr*gw1)
    b1.assign_sub(lr*gb1)
    w2.assign_sub(lr*gw2)
    b2.assign_sub(lr*gb2)
    print("**************************************************")
    print("NEW UPDATES")
    print("**************************************************")
    print(" the updated 1st layer weights are:\n",w1.numpy())
    print("--------------------------------------------------")
    print(" the updated 2nd layer weights are:\n",w2.numpy())
    print("--------------------------------------------------")
    print(" the updated 1st layer bias are:\n",b1.numpy())
    print("--------------------------------------------------")
    print(" the updated 2nd layer bias are:\n",b2.numpy())


    return w1, b1, w2, b2,loss

```

In [17]:
model.fit(X,Y.values,epochs=10,batch_size=32)

Epoch 1/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 124.4578
Epoch 2/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 33.5342
Epoch 3/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 5.9887
Epoch 4/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.2764
Epoch 5/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.3812
Epoch 6/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.2279
Epoch 7/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.1926
Epoch 8/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.1954
Epoch 9/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.1809
Epoch 10/10
16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.1825

In [18]:
model.predict(X)[:,0]

16/16 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

array([12.88932  , 13.374315 , 13.059608 , 13.0778675, 13.026318 ,
       12.783834 , 12.934261 , 13.21599  , 13.181791 , 12.902439 ,
       12.999615 , 13.260294 , 13.158844 , 12.807701 , 13.232012 ,
       12.844342 , 12.959307 , 13.297934 , 12.898721 , 12.837767 ,
       13.137572 , 12.880249 , 13.010822 , 13.220337 , 12.927248 ,
       13.100777 , 13.165804 , 13.095472 , 13.212324 , 13.219198 ,
       12.914917 , 13.247932 , 12.992502 , 13.239561 , 13.390156 ,
       13.343466 , 12.756142 , 13.038256 , 13.067482 , 13.172697 ,
       12.962242 , 12.889814 , 12.773523 , 13.0163765, 12.891592 ,
       12.831152 , 13.070091 , 13.059608 , 12.86706  , 13.335197 ,
       13.21599  , 13.282499 , 13.242365 , 13.024643 , 13.063236 ,
       13.020766 , 13.092915 , 13.3760195, 12.883007 , 13.014444 ,
       13.335197 , 13.236126 , 13.220337 , 13.206221 , 13.260294 ,
       12.790661 , 12.982548 , 12.780319 , 13.260813 , 13.127926 ,
       13.175623 , 13.270721 , 13.115664 , 13.051662 , 12.886168 ,
       12.910095 , 13.087772 , 13.220337 , 13.074779 , 13.195221 ,
       13.040047 , 13.39986  , 13.232405 , 13.024643 , 13.130482 ,
       13.137003 , 12.869588 , 12.9324875, 12.952015 , 12.888475 ,
       13.287827 , 13.11816  , 13.205933 , 13.16349  , 12.956362 ,
       13.194351 , 12.991119 , 13.269749 , 12.911126 , 13.432405 ,
       13.311243 , 13.080444 , 12.886168 , 13.137788 , 12.958183 ,
       13.258249 , 13.0615835, 13.494169 , 12.770067 , 12.810896 ,
       12.860862 , 13.123107 , 12.794088 , 13.149815 , 13.045481 ,
       12.717733 , 13.135172 , 12.759636 , 13.289804 , 12.988271 ,
       13.03458  , 12.923388 , 13.958544 , 13.046324 , 13.046324 ,
       12.911126 , 12.889814 , 12.869588 , 13.056968 , 13.258249 ,
       13.343466 , 12.953409 , 13.019251 , 13.162632 , 13.052067 ,
       13.120634 , 13.024643 , 13.045481 , 13.021896 , 13.154573 ,
       13.062241 , 12.875921 , 13.351215 , 13.504526 , 12.9596   ,
       12.973897 , 12.910509 , 13.30727  , 13.500348 , 13.003399 ,
       13.156942 , 12.877041 , 12.856812 , 12.892462 , 13.082598 ,
       12.935503 , 13.0778675, 12.834091 , 12.727816 , 13.010761 ,
       12.962242 , 13.072155 , 12.831141 , 12.976789 , 13.345926 ,
       13.012377 , 12.902439 , 12.790661 , 12.794088 , 12.863844 ,
       13.320288 , 13.118153 , 13.237452 , 12.982548 , 12.979672 ,
       13.038256 , 13.042768 , 12.911126 , 12.896146 , 13.188538 ,
       12.780319 , 12.897797 , 13.128277 , 13.071246 , 13.156942 ,
       13.296009 , 13.05892  , 13.038256 , 12.998224 , 13.40781  ,
       12.914206 , 12.941507 , 13.110756 , 13.366789 , 12.976789 ,
       13.021896 , 13.042768 , 13.110662 , 13.28236  , 12.879835 ,
       13.429419 , 13.4109535, 13.2594795, 13.232012 , 13.294058 ,
       13.022642 , 13.314993 , 13.209419 , 12.8541355, 13.2225   ,
       13.347696 , 12.814449 , 12.946108 , 13.051662 , 12.800827 ,
       12.993959 , 12.914206 , 13.502966 , 13.072691 , 12.879074 ,
       13.127926 , 12.705431 , 12.9324875, 13.227685 , 13.238213 ,
       13.3801   , 12.86706  , 13.500348 , 13.2843275, 12.834465 ,
       13.022064 , 12.773375 , 13.152197 , 13.509609 , 12.860617 ,
       12.950446 , 12.968086 , 12.814449 , 13.035549 , 13.201841 ,
       13.236126 , 13.317209 , 13.147425 , 12.963373 , 13.095741 ,
       13.013603 , 12.991119 , 12.99222  , 13.478522 , 12.995367 ,
       12.908038 , 13.043643 , 13.663881 , 12.837364 , 13.244432 ,
       12.780319 , 12.962242 , 13.191593 , 13.056968 , 13.16349  ,
       12.899586 , 13.170997 , 13.343466 , 13.188538 , 12.827515 ,
       12.7631235, 13.117783 , 13.0163765, 12.934261 , 13.067482 ,
       13.334293 , 13.234475 , 13.450355 , 13.123107 , 12.942457 ,
       13.202787 , 13.012377 , 13.125496 , 13.085575 , 13.14473  ,
       12.970997 , 12.742058 , 13.017185 , 12.976789 , 13.337171 ,
       13.292147 , 13.062241 , 12.911126 , 12.790661 , 12.7631235,
       12.79406  , 13.340481 , 13.090347 , 12.968086 , 12.938509 ,
       12.88932  , 13.040953 , 13.206221 , 12.837364 , 12.9018345,
       12.979672 , 13.251148 , 13.08     , 13.013603 , 12.985413 ,
       13.032835 , 13.098024 , 12.892985 , 12.863844 , 13.470463 ,
       13.43243  , 12.872759 , 13.204119 , 13.115265 , 12.969833 ,
       12.7631235, 12.989403 , 13.100777 , 13.283854 , 12.966326 ,
       12.988271 , 13.180222 , 13.2594795, 12.860617 , 13.048185 ,
       13.205004 , 12.817579 , 13.067482 , 12.727816 , 12.9372425,
       13.077974 , 13.077393 , 12.98963  , 13.158036 , 12.993959 ,
       13.062241 , 13.125572 , 13.05892  , 13.352968 , 13.1081505,
       12.904942 , 12.843884 , 12.935503 , 13.164001 , 13.122795 ,
       13.137572 , 13.056968 , 13.048998 , 13.1081505, 12.910095 ,
       12.810907 , 13.331575 , 13.042768 , 12.830807 , 12.998224 ,
       13.072691 , 13.32785  , 12.897797 , 13.115664 , 13.181791 ,
       13.284441 , 13.115664 , 12.941507 , 12.75937  , 12.841059 ,
       12.879835 , 13.207874 , 13.010822 , 12.883007 , 13.159302 ,
       12.857381 , 12.863844 , 13.182917 , 13.420273 , 12.950446 ,
       12.99222  , 12.92643  , 12.904942 , 13.227715 , 12.965168 ,
       13.017979 , 13.08173  , 12.911126 , 12.86002  , 12.77697  ,
       13.154167 , 12.830807 , 12.817579 , 13.479509 , 12.979672 ,
       13.418732 , 13.233213 , 12.972204 , 12.873823 , 13.038256 ,
       12.810907 , 13.193    , 13.409384 , 13.191593 , 12.904942 ,
       13.110662 , 13.161655 , 12.759636 , 12.942457 , 13.299755 ,
       12.727816 , 12.904942 , 12.921862 , 13.070284 , 13.103283 ,
       12.797506 , 12.938509 , 13.03458  , 12.911126 , 13.404644 ,
       13.092915 , 13.056968 , 12.831152 , 13.65439  , 13.042768 ,
       13.085966 , 13.344505 , 13.24376  , 12.872759 , 13.296009 ,
       12.914206 , 13.152197 , 13.023546 , 12.985413 , 12.908038 ,
       13.205004 , 13.042768 , 13.077393 , 12.893089 , 13.010822 ,
       13.092249 , 12.954943 , 13.026318 , 12.911126 , 12.895596 ,
       12.850881 , 13.241664 , 13.41408  , 13.128031 , 13.396879 ,
       12.886635 , 13.288246 , 12.787222 , 13.023546 , 13.01914  ,
       13.0778675, 12.993959 , 13.583099 , 12.876656 , 13.145027 ,
       12.872759 , 13.123107 , 13.220337 , 13.24376  , 12.830807 ,
       12.88932  , 13.375252 , 13.750023 , 12.776157 , 13.263607 ,
       13.110756 , 13.173313 , 13.026318 , 12.892462 , 13.08519  ,
       12.898721 , 13.615046 , 13.241664 , 13.080444 , 13.333389 ,
       12.897797 , 13.00243  , 12.8070545, 12.956362 , 13.210573 ,
       13.538855 , 12.894698 , 13.374315 , 13.120613 , 13.177927 ,
       12.79406  , 13.272425 , 13.074779 , 13.361647 , 13.132727 ,
       13.127926 , 12.966326 , 13.284441 , 12.773375 , 13.2843275,
       13.505568 , 12.898721 , 13.062241 , 12.790661 ], dtype=float32)

<div class="MuiBox-root css-1bi8ut6"><div class="text_component" data-testid="text-component"><p>In the videos above, we saw how the implementation of a training model we built earlier in TensorFlow required just a few lines of code using Keras. Quite interestingly, in the Keras model, we were passing 32 rows of input data as a batch for a training step, unlike what you have seen before. We do this instead of passing the whole data set through the training step because loading the whole data set while training the model will occupy a lot of memory and will slow down your training speed. Therefore, we split it into ‘<strong>mini-batches</strong>’ (usual size is 32) and pass each batch one by one through the training step. This is memory- and speed-efficient<b>.</b></p><p>&nbsp;</p><p dir="ltr">If the batch size is set to 1, then it becomes the <strong>stochastic gradient descent</strong> (which is shown in the TensorFlow code). If the batch size is set to the size of the data set, then it is called <strong>batch gradient descent</strong> (where we pass the whole data set through training in one go). If the batch size is a fraction of the whole data set, like 32 or 64, then it is mini-batch gradient descent.</p><p dir="ltr">&nbsp;</p>
    
## Process summary:
<ol><li dir="ltr" aria-level="1"><p dir="ltr" role="presentation">Define a simple sequential model to set the hidden layer(s) and the output layer. The following code allows us to define the simple sequential model:</p></li></ol><pre>model = keras.Sequential(
&nbsp;[ keras.layers.Dense(2, activation="sigmoid", input_shape=(X.shape[-1],)),
    keras.layers.Dense(1, activation="linear")
&nbsp;] )
</pre><ol start="2"><li dir="ltr" aria-level="1"><p dir="ltr" role="presentation">Display the properties and dimensions of each layer of the neural network.</p></li></ol><pre>model.summary()
</pre><ol start="3"><li dir="ltr" aria-level="1"><p dir="ltr" role="presentation">Define the type of optimiser to update the weights and biases.</p></li></ol><pre>model.compile(optimizer=keras.optimizers.SGD(), loss="mean_squared_error")
</pre><ol start="4"><li dir="ltr" aria-level="1"><p dir="ltr" role="presentation">Fit all the components defined above into one line of code to train the neural network.</p></li></ol><pre>model.fit(X,Y.values,epochs=10,batch_size=32)
</pre><ol start="5"><li dir="ltr" aria-level="1"><p dir="ltr" role="presentation">Obtain predictions on different input data.</p></li></ol><pre>model.predict(X)[:,0]
</pre><p dir="ltr">&nbsp;</p><p dir="ltr">Now, let's see how we can use Keras for a problem on <strong>unstructured </strong>data, i.e., <strong>MNIST</strong>. We will use Keras to train an <strong>image classifier</strong> on it.<strong>&nbsp;</strong></p><p dir="ltr">&nbsp;</p><p dir="ltr"><strong>NOTE:&nbsp;</strong>The code can be run on Google Colab, jupyter notebook, or other compatible platforms. However, Google Colab is preferable as it requires a minimal initial setup.</p><p dir="ltr">Google Colab is a free cloud service and provides free GPU access.&nbsp;You can <a target="_blank" href="https://medium.com/deep-learning-turkey/google-colab-free-gpu-tutorial-e113627b9f5d">learn how to get started with Google Colab here</a>.&nbsp;</p><p dir="ltr">&nbsp;</p><p>The datasets can be downloaded below. (You can upload the zip file directly to Google Colab as the inbuilt codes are written in a notebook to extract the datasets.)</p></div></div>