## 1. <font color = red> Importing the Required Libraries and the Embeddings </font>

In [1]:
# Import required libraries

import numpy as np
import pandas as pd
import ast

In [2]:
# from google.colab import drive
# drive.mount('/content/drive')

In [3]:
input_path = './'

In [4]:
section_chunk_embeddings = pd.read_csv(input_path + 'section_chunk_embeddings.csv')

In [5]:
section_chunk_embeddings.info()

<class 'pandas.DataFrame'>
RangeIndex: 95 entries, 0 to 94
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Title          95 non-null     str
 1   Section Title  95 non-null     str
 2   Chunk Text     95 non-null     str
 3   Embeddings     95 non-null     str
dtypes: str(4)
memory usage: 787.9 KB

In [6]:
section_chunk_embeddings['Embeddings'] = section_chunk_embeddings['Embeddings'].apply(lambda x: x[7:][:-1])

In [7]:
section_chunk_embeddings['Embeddings'][0]

'[-4.5234e-02, -2.8654e-02, -8.4308e-02,  2.5436e-02, -3.5023e-02,\n         4.6069e-02,  6.7365e-02, -5.0723e-03,  1.2327e-01, -2.2020e-02,\n        -7.0932e-02,  4.1421e-02,  7.1477e-02,  4.5033e-02, -3.5538e-02,\n         9.7735e-03,  1.2935e-02,  2.5428e-02, -7.0864e-03,  7.6964e-03,\n         5.1681e-02, -1.6334e-02,  3.5429e-02, -3.3055e-02, -4.9527e-02,\n        -3.3702e-02,  1.6654e-02, -7.6722e-02, -8.4791e-02,  6.0315e-02,\n        -1.9919e-02, -7.8969e-02, -2.5472e-02, -1.9788e-02,  8.9350e-03,\n         8.0604e-02,  4.3905e-02, -1.0023e-02, -1.0294e-02, -1.2882e-03,\n        -1.4940e-02,  4.8730e-02,  4.0125e-02,  4.1119e-02,  5.5447e-02,\n        -6.6756e-02, -1.5770e-02, -8.0316e-02,  4.1568e-04, -1.0977e-01,\n        -3.1936e-02,  1.1492e-01, -1.9863e-02,  2.5466e-02, -1.9720e-03,\n        -6.6851e-02, -8.9303e-03,  3.7322e-03, -6.4495e-03, -6.6111e-02,\n        -4.6566e-02,  4.1288e-03,  1.5850e-02, -1.3968e-02,  7.4380e-02,\n         1.9631e-02,  8.9285e-03, -1.1776e-02,  4.0015e-02, -6.7040e-02,\n        -7.9944e-02,  3.9827e-02, -1.1427e-02, -7.1061e-02, -6.1366e-02,\n        -7.9808e-02,  2.7580e-02,  1.2659e-01, -4.6352e-02, -9.6243e-02,\n        -1.6517e-02, -9.4117e-02,  3.2030e-02,  1.0306e-01, -2.0143e-02,\n         9.3839e-02, -4.0228e-02,  5.6349e-02,  1.3214e-02,  2.2488e-02,\n         8.5113e-02,  6.3428e-02, -5.9753e-03, -1.2993e-02, -3.3056e-02,\n        -3.2579e-02, -3.3255e-02,  2.4634e-02, -5.9211e-02,  1.6756e-02,\n         3.0338e-02, -5.1782e-02, -7.8918e-03, -1.0309e-01,  1.2015e-01,\n         1.4392e-02,  1.9945e-02, -2.0385e-03, -3.2688e-02, -2.7260e-02,\n         4.4872e-02,  3.0128e-02,  5.4345e-02,  1.4244e-01,  7.7157e-02,\n         1.0606e-01, -5.0621e-02, -4.6598e-02, -1.6300e-03,  5.7642e-02,\n         4.5311e-02,  3.6823e-02, -8.8967e-03,  2.9674e-02, -1.0218e-01,\n        -5.3811e-02,  8.1681e-03,  4.1447e-33, -3.6037e-02,  2.1500e-02,\n         1.3945e-02, -4.3284e-02, -3.6263e-02, -3.2515e-02, -7.0684e-03,\n         1.8384e-02,  5.1318e-03,  1.1544e-03, -2.6331e-02, -9.9720e-02,\n        -4.7559e-02, -3.9180e-02, -2.9521e-02, -1.1110e-02, -1.7699e-02,\n        -9.3034e-03,  6.8162e-02, -1.4682e-02, -2.8374e-02,  3.4010e-03,\n         1.8979e-02,  3.3686e-02, -1.3565e-01, -2.4133e-02, -3.9634e-02,\n         1.2597e-02, -4.0435e-03, -2.1729e-02, -2.3127e-02,  8.4730e-02,\n         8.2744e-02, -7.1768e-02,  3.7460e-02, -7.9695e-02, -1.2376e-02,\n         1.9695e-02,  3.9581e-02,  7.6759e-02, -5.6860e-02, -4.7583e-03,\n         3.4536e-03,  1.6844e-02, -1.7179e-02,  1.0698e-02,  2.9980e-02,\n         3.0546e-02, -3.9667e-02,  8.0675e-02, -2.3901e-02,  1.0354e-02,\n         3.7521e-02, -1.1363e-01, -1.6871e-01,  2.6907e-02, -1.6632e-02,\n        -9.1899e-02,  5.9327e-02,  1.0572e-01,  4.1078e-02, -4.0180e-02,\n         1.2778e-03, -9.7845e-04, -6.6330e-02, -3.8704e-02,  6.4321e-02,\n         5.8743e-02, -9.3135e-02,  3.4084e-02, -5.2802e-02,  4.5298e-02,\n         7.5835e-02,  9.4569e-03,  3.7134e-02, -4.8106e-02, -1.1236e-02,\n         9.0577e-02, -5.8917e-02,  2.4782e-02, -9.6541e-04,  1.2165e-02,\n        -2.1696e-02, -3.3722e-02, -6.5985e-02,  9.3755e-03,  2.4892e-02,\n        -3.9337e-02,  3.1643e-02,  6.1021e-02,  5.9508e-02, -7.8741e-03,\n        -7.5429e-02, -4.9240e-02,  6.6423e-02, -5.9739e-33,  6.9160e-02,\n        -7.4962e-02, -6.2510e-02, -6.7066e-02, -8.5856e-03,  2.3655e-02,\n        -2.1390e-04, -1.4248e-02,  6.7374e-02, -2.7431e-02, -5.0330e-02,\n         2.3976e-02,  6.0867e-02,  9.9447e-02, -4.2295e-02,  6.9748e-02,\n        -1.0459e-01,  1.3661e-02, -2.4690e-03,  3.0968e-02, -2.5578e-02,\n        -5.3843e-02, -7.6069e-02,  1.7349e-02,  3.7549e-02,  2.7253e-02,\n        -5.7048e-02,  8.4914e-02, -4.0203e-02,  1.6482e-02,  1.2505e-02,\n        -5.3001e-02, -5.8470e-02,  3.8597e-02, -9.5243e-02,  2.4469e-02,\n         8.6643e-02, -1.1588e-01, -8.6336e-03,  5.1169e-02,  1.3970e-02,\n        -1.7164e-02, -5.8103e-02, -2.8197e-02, -2.1913e-04,  2.4897e-02,\n        -3.9765e-02,  2.3565e-02, -3.6750e-02, -6.7453e-02, -4.3241e-02,\n         7.2810e-02,  1.1511e-02,  1.9358e-02, -1.5918e-02,  2.0774e-02,\n         6.5907e-03,  2.4775e-02,  3.2906e-02,  2.5736e-02, -9.0174e-02,\n        -2.9743e-02,  4.7466e-04, -1.2408e-02,  4.2700e-03, -5.9547e-02,\n         2.5754e-02, -4.5089e-02, -3.1676e-02,  1.6109e-02,  2.2336e-02,\n        -7.2422e-02,  2.2487e-02, -6.5939e-02, -3.0449e-02,  5.6920e-02,\n         2.7630e-02, -3.3678e-02, -1.0868e-01, -3.4034e-02,  4.8588e-02,\n         3.1120e-02,  3.3269e-02, -8.3862e-04, -5.4757e-02,  4.2043e-02,\n         1.3980e-01, -2.0062e-02, -3.3530e-02, -9.0847e-02,  3.1187e-02,\n        -6.3140e-02,  5.0703e-02,  3.3591e-02,  1.2184e-02, -5.6206e-08,\n        -9.6964e-02,  1.3879e-03, -5.2511e-02,  3.7321e-02,  5.8370e-03,\n         5.0213e-02,  9.5032e-03,  3.8808e-02, -7.4626e-02, -1.1665e-02,\n        -3.2753e-02, -8.1995e-02,  1.9638e-02, -3.6065e-02, -5.9336e-02,\n         1.2637e-02,  3.7244e-02,  2.5890e-02,  6.3643e-02,  4.5094e-02,\n         4.0999e-02, -8.0470e-02,  6.8106e-02, -1.0694e-02,  1.3259e-02,\n         1.4643e-02, -1.2594e-03, -1.8950e-02,  3.3221e-02,  5.4943e-02,\n         2.6805e-02, -3.8677e-02,  3.2383e-02,  1.3247e-02,  4.5914e-02,\n        -3.7439e-02, -4.4742e-02,  2.6282e-02,  6.7187e-02,  2.2813e-02,\n         1.2982e-02,  4.9961e-02, -5.3652e-02, -2.0418e-02,  5.2219e-02,\n         2.2305e-02, -4.6701e-02, -4.7386e-02,  9.4230e-02,  8.6832e-02,\n         9.7432e-02, -4.3961e-03,  4.8399e-02, -1.4645e-02,  7.6914e-02,\n        -4.0002e-02,  1.6663e-02, -4.8298e-03, -6.2167e-03,  1.8933e-02,\n         6.2250e-02, -1.3494e-02,  4.2968e-03, -6.5220e-02]'

In [8]:
section_chunk_embeddings['Embeddings'] = section_chunk_embeddings['Embeddings'].apply(lambda x: ast.literal_eval(x))

In [9]:
section_chunk_embeddings.info()

<class 'pandas.DataFrame'>
RangeIndex: 95 entries, 0 to 94
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Title          95 non-null     str
 1   Section Title  95 non-null     str
 2   Chunk Text     95 non-null     str
 3   Embeddings     95 non-null     object
dtypes: object(1), str(3)
memory usage: 267.7+ KB

In [10]:
section_chunk_embeddings

,Title,Section Title,Chunk Text,Embeddings
0,The Shawshank Redemption,Introduction,The Shawshank Redemption is a 1994 American pr...,"[-0.045234, -0.028654, -0.084308, 0.025436, -0..."
1,The Shawshank Redemption,Plot,"In early 1947, Portland, Maine, banker Andy Du...","[0.014254, 0.0067946, -0.037625, -0.016357, -0..."
2,The Shawshank Redemption,Cast,Tim Robbins as Andy Dufresne: A banker sentenc...,"[-0.053459, -0.053774, -0.12491, -0.012516, -0..."
3,The Shawshank Redemption,Analysis,The film has been interpreted as being grounde...,"[-0.055615, 0.051125, -0.083388, -0.0088534, -..."
4,The Shawshank Redemption,Development,Darabont first collaborated with author Stephe...,"[-0.033833, -0.034259, -0.022021, 0.083097, -0..."
...,...,...,...,...
90,Goodfellas,Box office,"Goodfellas grossed $6.3 million from 1,070 the...","[0.028257, -0.062327, -0.015942, 0.078449, -0...."
91,Goodfellas,Critical response,According to review aggregator Rotten Tomatoes...,"[-0.010413, -0.031451, -0.12268, 0.024364, 0.0..."
92,Goodfellas,Lists,The film was ranked the best of 1990 by Roger ...,"[-0.0047438, -0.095356, -0.063817, 0.019216, 0..."
93,Goodfellas,Accolades,It became one of the eight films to win Best P...,"[-0.0066345, -0.07772, -0.01668, 9.9736e-05, 0..."
94,Goodfellas,Legacy,Goodfellas is No. 94 on the American Film Inst...,"[-0.0017614, -0.056696, -0.071819, 0.0085434, ..."

In [11]:
section_chunk_embeddings['Embeddings'][0]

[-0.045234,
 -0.028654,
 -0.084308,
 0.025436,
 -0.035023,
 0.046069,
 0.067365,
 -0.0050723,
 0.12327,
 -0.02202,
 -0.070932,
 0.041421,
 0.071477,
 0.045033,
 -0.035538,
 0.0097735,
 0.012935,
 0.025428,
 -0.0070864,
 0.0076964,
 0.051681,
 -0.016334,
 0.035429,
 -0.033055,
 -0.049527,
 -0.033702,
 0.016654,
 -0.076722,
 -0.084791,
 0.060315,
 -0.019919,
 -0.078969,
 -0.025472,
 -0.019788,
 0.008935,
 0.080604,
 0.043905,
 -0.010023,
 -0.010294,
 -0.0012882,
 -0.01494,
 0.04873,
 0.040125,
 0.041119,
 0.055447,
 -0.066756,
 -0.01577,
 -0.080316,
 0.00041568,
 -0.10977,
 -0.031936,
 0.11492,
 -0.019863,
 0.025466,
 -0.001972,
 -0.066851,
 -0.0089303,
 0.0037322,
 -0.0064495,
 -0.066111,
 -0.046566,
 0.0041288,
 0.01585,
 -0.013968,
 0.07438,
 0.019631,
 0.0089285,
 -0.011776,
 0.040015,
 -0.06704,
 -0.079944,
 0.039827,
 -0.011427,
 -0.071061,
 -0.061366,
 -0.079808,
 0.02758,
 0.12659,
 -0.046352,
 -0.096243,
 -0.016517,
 -0.094117,
 0.03203,
 0.10306,
 -0.020143,
 0.093839,
 -0.040228,
 0.056349,
 0.013214,
 0.022488,
 0.085113,
 0.063428,
 -0.0059753,
 -0.012993,
 -0.033056,
 -0.032579,
 -0.033255,
 0.024634,
 -0.059211,
 0.016756,
 0.030338,
 -0.051782,
 -0.0078918,
 -0.10309,
 0.12015,
 0.014392,
 0.019945,
 -0.0020385,
 -0.032688,
 -0.02726,
 0.044872,
 0.030128,
 0.054345,
 0.14244,
 0.077157,
 0.10606,
 -0.050621,
 -0.046598,
 -0.00163,
 0.057642,
 0.045311,
 0.036823,
 -0.0088967,
 0.029674,
 -0.10218,
 -0.053811,
 0.0081681,
 4.1447e-33,
 -0.036037,
 0.0215,
 0.013945,
 -0.043284,
 -0.036263,
 -0.032515,
 -0.0070684,
 0.018384,
 0.0051318,
 0.0011544,
 -0.026331,
 -0.09972,
 -0.047559,
 -0.03918,
 -0.029521,
 -0.01111,
 -0.017699,
 -0.0093034,
 0.068162,
 -0.014682,
 -0.028374,
 0.003401,
 0.018979,
 0.033686,
 -0.13565,
 -0.024133,
 -0.039634,
 0.012597,
 -0.0040435,
 -0.021729,
 -0.023127,
 0.08473,
 0.082744,
 -0.071768,
 0.03746,
 -0.079695,
 -0.012376,
 0.019695,
 0.039581,
 0.076759,
 -0.05686,
 -0.0047583,
 0.0034536,
 0.016844,
 -0.017179,
 0.010698,
 0.02998,
 0.030546,
 -0.039667,
 0.080675,
 -0.023901,
 0.010354,
 0.037521,
 -0.11363,
 -0.16871,
 0.026907,
 -0.016632,
 -0.091899,
 0.059327,
 0.10572,
 0.041078,
 -0.04018,
 0.0012778,
 -0.00097845,
 -0.06633,
 -0.038704,
 0.064321,
 0.058743,
 -0.093135,
 0.034084,
 -0.052802,
 0.045298,
 0.075835,
 0.0094569,
 0.037134,
 -0.048106,
 -0.011236,
 0.090577,
 -0.058917,
 0.024782,
 -0.00096541,
 0.012165,
 -0.021696,
 -0.033722,
 -0.065985,
 0.0093755,
 0.024892,
 -0.039337,
 0.031643,
 0.061021,
 0.059508,
 -0.0078741,
 -0.075429,
 -0.04924,
 0.066423,
 -5.9739e-33,
 0.06916,
 -0.074962,
 -0.06251,
 -0.067066,
 -0.0085856,
 0.023655,
 -0.0002139,
 -0.014248,
 0.067374,
 -0.027431,
 -0.05033,
 0.023976,
 0.060867,
 0.099447,
 -0.042295,
 0.069748,
 -0.10459,
 0.013661,
 -0.002469,
 0.030968,
 -0.025578,
 -0.053843,
 -0.076069,
 0.017349,
 0.037549,
 0.027253,
 -0.057048,
 0.084914,
 -0.040203,
 0.016482,
 0.012505,
 -0.053001,
 -0.05847,
 0.038597,
 -0.095243,
 0.024469,
 0.086643,
 -0.11588,
 -0.0086336,
 0.051169,
 0.01397,
 -0.017164,
 -0.058103,
 -0.028197,
 -0.00021913,
 0.024897,
 -0.039765,
 0.023565,
 -0.03675,
 -0.067453,
 -0.043241,
 0.07281,
 0.011511,
 0.019358,
 -0.015918,
 0.020774,
 0.0065907,
 0.024775,
 0.032906,
 0.025736,
 -0.090174,
 -0.029743,
 0.00047466,
 -0.012408,
 0.00427,
 -0.059547,
 0.025754,
 -0.045089,
 -0.031676,
 0.016109,
 0.022336,
 -0.072422,
 0.022487,
 -0.065939,
 -0.030449,
 0.05692,
 0.02763,
 -0.033678,
 -0.10868,
 -0.034034,
 0.048588,
 0.03112,
 0.033269,
 -0.00083862,
 -0.054757,
 0.042043,
 0.1398,
 -0.020062,
 -0.03353,
 -0.090847,
 0.031187,
 -0.06314,
 0.050703,
 0.033591,
 0.012184,
 -5.6206e-08,
 -0.096964,
 0.0013879,
 -0.052511,
 0.037321,
 0.005837,
 0.050213,
 0.0095032,
 0.038808,
 -0.074626,
 -0.011665,
 -0.032753,
 -0.081995,
 0.019638,
 -0.036065,
 -0.059336,
 0.012637,
 0.037244,
 0.02589,
 0.063643,
 0.045094,
 0.040999,
 -0.08047,
 0.068106,
 -0.010694,
 0.013259,
 0.014643,
 -0.0012594,
 -0.01895,
 0.033221,
 0.054943,
 0.026805,
 -0.038677,
 0.032383,
 0.013247,
 0.045914,
 -0.037439,
 -0.044742,
 0.026282,
 0.067187,
 0.022813,
 0.012982,
 0.049961,
 -0.053652,
 -0.020418,
 0.052219,
 0.022305,
 -0.046701,
 -0.047386,
 0.09423,
 0.086832,
 0.097432,
 -0.0043961,
 0.048399,
 -0.014645,
 0.076914,
 -0.040002,
 0.016663,
 -0.0048298,
 -0.0062167,
 0.018933,
 0.06225,
 -0.013494,
 0.0042968,
 -0.06522]

In [12]:
type(section_chunk_embeddings['Embeddings'][0])

list

## 2. <font color = red> ChromaDB </font>

### <font color = red> 2.1 Adding documents/embeddings to ChromaDB and working with Collections </font>

You can add embeddings or chunks of text directly to chroma using their collection methods.

* **`.create_collection()`**
* **`.list_collections()`**
* **`.delete_collections()`**


* **`collection.add()`**
* `collection.peek()`
* `collection.get()`

In [13]:
# Pip install chromaDB

!pip install chromadb

zsh:1: command not found: pip

In [14]:
# Import ChromaDB and get the Chroma client

import chromadb
chroma_client = chromadb.PersistentClient()

In [15]:
# Create a collection to store the embeddings. Collections in Chroma are where you can store your embeddings, documents, and any additional metadata.

collection = chroma_client.get_or_create_collection(name="Semantic_Search_with_Chromadb")

In [16]:
# Add the documents, embeddings, and ids into the collection

collection.add(
    embeddings = section_chunk_embeddings['Embeddings'].to_list(),
    documents = section_chunk_embeddings['Chunk Text'].to_list(),
    ids = [str(i) for i in range(0, len(section_chunk_embeddings['Embeddings']))],
)

In [17]:
# Peek at the initial elements of the collection

collection.peek()

{'ids': ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'],
 'embeddings': array([[-0.045234 , -0.028654 , -0.084308 , ..., -0.013494 ,  0.0042968,
         -0.06522  ],
        [ 0.014254 ,  0.0067946, -0.037625 , ..., -0.0097042,  0.038454 ,
         -0.075619 ],
        [-0.053459 , -0.053774 , -0.12491  , ..., -0.019534 ,  0.059722 ,
         -0.062948 ],
        ...,
        [-0.033779 , -0.035569 ,  0.0085257, ...,  0.012246 , -0.026384 ,
          0.016961 ],
        [-0.068227 , -0.04472  , -0.06537  , ...,  0.067921 , -0.020769 ,
         -0.0386   ],
        [-0.022781 , -0.022584 , -0.095704 , ..., -0.10307  , -0.047831 ,
          0.043886 ]], shape=(10, 384)),
 'documents': ['The Shawshank Redemption is a 1994 American prison drama film written and directed by Frank Darabont, based on the 1982 Stephen King novella Rita Hayworth and Shawshank Redemption. The film tells the story of banker Andy Dufresne (Tim Robbins), who is sentenced to life in Shawshank State Penitentiary for the murders of his wife and her lover, despite his claims of innocence. Over the following two decades, he befriends a fellow prisoner, contraband smuggler Ellis "Red" Redding (Morgan Freeman), and becomes instrumental in a money laundering operation led by the prison warden Samuel Norton (Bob Gunton). William Sadler, Clancy Brown, Gil Bellows, and James Whitmore appear in supporting roles.\nDarabont purchased the film rights to King\'s story in 1987, but development did not begin until five years later, when he wrote the script over an eight-week period. Two weeks after submitting his script to Castle Rock Entertainment, Darabont secured a $25 million budget to produce The Shawshank Redemption, which started pre-production in January 1993. While the film is set in Maine, principal photography took place from June to August 1993 almost entirely in Mansfield, Ohio, with the Ohio State Reformatory serving as the eponymous penitentiary. The project attracted many stars for the role of Andy, including Tom Hanks, Tom Cruise, and Kevin Costner. Thomas Newman provided the film\'s score.\nWhile The Shawshank Redemption received critical acclaim upon its release—particularly for its story, the performances of Robbins and Freeman, Newman\'s score, Darabont\'s direction and screenplay and Roger Deakins\' cinematography—the film was a box-office disappointment, earning only $16 million during its initial theatrical run. Many reasons were cited for its failure at the time, including competition from the films Pulp Fiction and Forrest Gump, the general unpopularity of prison films, its lack of female characters, and even the title, which was considered to be confusing for audiences. It went on to receive multiple award nominations, including seven Academy Award nominations, and a theatrical re-release that, combined with international takings, increased the film\'s box-office gross to $73.3 million.\nOver 320,000 VHS rental copies were shipped throughout the United States, and on the strength of its award nominations and word of mouth, it became one of the top video rentals of 1995. The broadcast rights were acquired following the purchase of Castle Rock by Turner Broadcasting System, and it was shown regularly on the TNT network starting in 1997, further increasing its popularity. Decades after its release, the film was still broadcast regularly, and is popular in several countries, with audience members and celebrities citing it as a source of inspiration or naming it a favorite in various surveys, leading to its recognition as one of the most "beloved" films ever made. In 2015, the United States Library of Congress selected the film for preservation in the National Film Registry, finding it "culturally, historically, or aesthetically significant".',
  'In early 1947, Portland, Maine, banker Andy Dufresne arrives at Shawshank State Prison to serve two consecutive life sentences for murdering his wife and her lover. He is befriended by Ellis "Red" Redding, a contraband smuggler serving a life sentence, who procures a rock hammer and a large poster of Rita Hayworth for Andy. Assigned to work in the prison laundry, Andy is frequently sexually assaulted by "the Sisters" and their leader, Bogs Diamond.\nIn 1949, Andy overhears the captain of the guards, Byron Hadley, complaining about being taxed on an inheritance and offers to help him shelter the money legally. After an assault by the Sisters nearly kills Andy, Hadley beats and cripples Bogs, who is subsequently transferred to another prison; Andy is not attacked again. Warden Samuel Norton meets Andy and reassigns him to the prison library to assist elderly inmate Brooks Hatlen, a front to use Andy\'s financial expertise to manage financial matters for other prison staff, guards from other prisons, and the warden himself. Andy begins writing weekly letters to the state legislature requesting funds to improve the prison\'s decrepit library.\nBrooks is paroled in 1954 after serving 50 years, but he cannot adjust to the outside world and eventually hangs himself. The legislature sends a library donation that includes a recording of The Marriage of Figaro; Andy plays an excerpt over the public address system and is punished with solitary confinement. After his release from solitary, Andy explains to a dismissive Red that hope is what gets him through his sentence. In 1963, Norton begins exploiting prison labor for public works, profiting by undercutting skilled labor costs and receiving bribes. Andy launders the money using the alias "Randall Stephens".\nIn 1965, Andy and Red befriend Tommy Williams, a young prisoner incarcerated for burglary. A year later, Andy helps him pass his General Educational Development (GED) exam. Tommy reveals to Red and Andy that his cellmate at another prison had claimed responsibility for the murders of which Andy was convicted. Andy brings the information to Norton who refuses to listen and, when Andy mentions the money laundering, sends Andy to solitary confinement and has Hadley fatally shoot Tommy under the guise of an escape attempt. Andy refuses to continue the money laundering, but Norton threatens to destroy the library, remove Andy\'s protection by the guards, and move him to worse conditions. Andy is released from solitary confinement after two months, and he tells a skeptical Red that he dreams of living in Zihuatanejo, a Mexican town on the Pacific coast. Andy also tells him of a specific hayfield near Buxton, asking Red to promise, once he is released, to retrieve a package that Andy buried there. Red worries about Andy\'s mental well-being, especially when he learns Andy asked a fellow inmate for some rope.\nAt the next day\'s roll call, the guards find Andy\'s cell empty. An irate Norton throws a rock at a poster of Raquel Welch hanging on the cell wall, revealing a tunnel that Andy had dug with his rock hammer over the past 19 years. The previous night, Andy used the rope to escape through the tunnel and prison sewage pipe, taking Norton\'s suit, shoes, and ledger, containing evidence of the money laundering. While guards search for him, Andy poses as Randall Stephens, withdraws over $370,000 of the laundered money from several banks, and mails the ledger and other evidence of the corruption and murders at Shawshank to a local newspaper. State police arrive at Shawshank and take Hadley into custody, while Norton commits suicide to avoid arrest.\nThe following year, Red is paroled after serving 40 years but struggles to adapt to life outside prison and fears that he never will. Remembering his promise to Andy, he visits Buxton and finds a cache containing money and a letter asking him to come to Zihuatanejo. Red violates his parole by traveling to Fort Hancock, Texas, and crossing the border into Mexico, admitting that he finally feels hope. He finds Andy sanding an old boat on a Zihuatanejo beach, and the two reunited friends happily embrace.',
  'Tim Robbins as Andy Dufresne: A banker sentenced to life in prison in 1947 for the murder of his wife and her lover\nMorgan Freeman as Ellis Boyd "Red" Redding: A prison contraband smuggler who befriends Andy\nBob Gunton as Samuel Norton: The pious and cruel warden of Shawshank penitentiary\nWilliam Sadler as Heywood: A member of Red\'s gang of long-serving convicts\nClancy Brown as Byron Hadley: The brutal captain of the prison guards\nGil Bellows as Tommy Williams: A young convict imprisoned for burglary in 1965\nJames Whitmore as Brooks Hatlen: The elderly prison librarian, imprisoned at Shawshank for over five decadesThe cast also includes Mark Rolston as Bogs Diamond, the head of "the Sisters" gang and a prison rapist; Jeffrey DeMunn as the prosecuting attorney in Dufresne\'s trial; Alfonso Freeman as Fresh Fish Con; Ned Bellamy and Don McManus as, respectively, prison guards Youngblood and Wiley; and Dion Anderson as Head Bull Haig. Renee Blaine portrays Andy\'s wife, and Scott Mann portrays her golf-instructor lover Glenn Quentin. Frank Medrano plays Fat Ass, one of Andy\'s fellow new inmates who is beaten to death by Hadley, and Bill Bolender plays Elmo Blatch, a convict who may actually be responsible for the crimes for which Andy is convicted. James Kisicki and Claire Slemmer portray the Maine National Bank manager and a teller, respectively.',
  'The film has been interpreted as being grounded in Christian mysticism. Andy is offered as a messianic, Christ-like figure, with Red describing him early in the film as having an aura that engulfs and protects him from Shawshank. The scene in which Andy and several inmates tar the prison roof can be seen as a recreation of the Last Supper, with Andy obtaining beer/wine for the twelve inmates/disciples as Freeman describes them as the "lords of all creation" invoking Jesus\' blessing. Director Frank Darabont responded that this was not his deliberate intention, but he wanted people to find their own meaning in the film. The discovery of The Marriage of Figaro record is described in the screenplay as akin to finding the Holy Grail, bringing the prisoners to a halt, and causing the sick to rise up in their beds.Early in the film, Warden Norton quotes Jesus Christ to describe himself to Andy, saying, "I am the light of the world", declaring himself Andy\'s savior, but this description can also reference Lucifer, the bearer of light. Indeed, the warden does not enforce the general rule of law, but chooses to enforce his own rules and punishments as he sees fit, becoming a law unto himself, like the behavior of Satan. The warden has also been compared to former United States President Richard Nixon. Norton\'s appearance and public addresses can be seen to mirror Nixon\'s. Similarly, Norton projects an image of a holy man, speaking down sanctimoniously to the servile masses while running corrupt scams, like those of which Nixon was accused.\nZihuatanejo has been interpreted as an analog for heaven or paradise. In the film, Andy describes it as a place with no memory, offering absolution from his sins by forgetting about them or allowing them to be washed away by the Pacific Ocean, whose name means "peaceful". The possibility of escaping to Zihuatanejo is only raised after Andy admits that he feels responsible for his wife\'s death. Similarly, Red\'s freedom is only earned once he accepts he cannot save himself or atone for his sins. Freeman has described Red\'s story as one of salvation as he is not innocent of his crimes, unlike Andy who finds redemption. While some Christian viewers interpret Zihuatanejo as heaven, film critic Mark Kermode wrote that it can also be interpreted as a Nietzschean form of guiltlessness achieved outside traditional notions of good and evil, where the amnesia offered is the destruction rather than forgiveness of sin, meaning Andy\'s aim is secular and atheistic. Just as Andy can be interpreted as a Christ-like figure, he can be seen as a Zarathustra-like prophet offering escape through education and the experience of freedom. Film critic Roger Ebert argued that The Shawshank Redemption is an allegory for maintaining one\'s feeling of self-worth when placed in a hopeless position. Andy\'s integrity is an important theme in the story line, especially in prison, where integrity is lacking.Robbins himself believes that the concept of Zihuatanejo resonates with audiences because it represents a form of escape that can be achieved after surviving for many years within whatever "jail" someone finds themselves in, whether a bad relationship, job, or environment. Robbins said that it is important that such a place exists for us. Isaac M. Morehouse suggests that the film provides a great illustration of how characters can be free, even in prison, or imprisoned, even in freedom, based on their outlooks on life. Philosopher Jean-Paul Sartre described freedom as an ongoing project that requires attention and resilience, without which a person begins to be defined by others or institutions, mirroring Red\'s belief that inmates become dependent on the prison to define their lives. Andy displays resilience through rebellion, by playing music over the prison loudspeaker, and refusing to continue with the money-laundering scam.Many elements can be considered as tributes to the power of cinema. In the prison theater, the inmates watch the film Gilda (1946), but this scene was originally intended to feature The Lost Weekend (1945). The interchangeability of the films used in the prison theater suggests that it is the cinematic experience and not the subject that is key to the scene, allowing the men to escape the reality of their situation. Immediately following this scene, Andy is assaulted by the Sisters in the projector room and uses a film reel to help fight them off. At the end of the film, Andy passes through a hole in his cell hidden by a movie poster to escape both his cell and ultimately Shawshank.Andy and Red\'s relationship has been described as a nonsexual story between two men, that few other films offer, as the friendship is not built on conducting a caper, car chases, or developing a relationship with women. Philosopher Alexander Hooke argued that Andy and Red\'s true freedom is their friendship, being able to share joy and humor with each other.',
  'Darabont first collaborated with author Stephen King in 1983 on the short film adaptation of "The Woman in the Room", buying the rights from him for $1—a Dollar Deal that King used to help new directors build a résumé by adapting his short stories. After receiving his first screenwriting credit in 1987 for A Nightmare on Elm Street 3: Dream Warriors, Darabont returned to King with $5,000 to purchase the rights to adapt Rita Hayworth and Shawshank Redemption, a 96-page novella from King\'s 1982 collection Different Seasons, written to explore genres other than the horror stories for which he was commonly known. Although King did not understand how the story, largely focused on Red contemplating his fellow prisoner Andy, could be turned into a feature film, Darabont believed it was "obvious". King never cashed the $5,000 check from Darabont; he later framed it and returned it to Darabont accompanied by a note which read: "In case you ever need bail money. Love, Steve."Five years later, Darabont wrote the script over an eight-week period. He expanded on elements of King\'s story. Brooks, who in the novella is a minor character who dies in a retirement home, became a tragic character who eventually hanged himself. Tommy, who in the novella trades his evidence exonerating Andy for transfer to a nicer prison, in the screenplay is murdered on the orders of Warden Norton, who is a composite of several warden characters in King\'s story. Darabont opted to create a single warden character to serve as the primary antagonist. Among his inspirations, Darabont listed the works of director Frank Capra, including Mr. Smith Goes to Washington (1939) and It\'s a Wonderful Life (1946), describing them as tall tales; Darabont likened The Shawshank Redemption to a tall tale more than a prison movie. He also cited Goodfellas (1990) as an inspiration on the use of dialogue to illustrate the passage of time in the script, and the prison drama Birdman of Alcatraz (1962) directed by John Frankenheimer. While later scouting filming locations, Darabont happened upon Frankenheimer who was scouting for his own prison-set project Against the Wall. Darabont recalled that Frankenheimer took time out from his scouting to provide Darabont with encouragement and advice.At the time, prison-based films were not considered likely box-office successes, but Darabont\'s script was read by then-Castle Rock Entertainment producer Liz Glotzer, whose interest in prison stories and reaction to the script, led her to threaten to quit if Castle Rock did not produce The Shawshank Redemption. Director and Castle Rock co-founder Rob Reiner also liked the script. He offered Darabont between $2.4 million and $3 million to allow him to direct it himself. Reiner, who had previously adapted King\'s 1982 novella The Body into the 1986 film Stand by Me, planned to cast Tom Cruise as Andy and Harrison Ford as Red.Castle Rock offered to finance any other film Darabont wanted to develop. Darabont seriously considered the offer, citing growing up poor in Los Angeles, believing it would elevate his standing in the industry, and that Castle Rock could have contractually fired him and given the film to Reiner anyway, but he chose to remain the director, saying in a 2014 Variety interview, "you can continue to defer your dreams in exchange for money and, you know, die without ever having done the thing you set out to do". Reiner served as Darabont\'s mentor on the project, instead. Within two weeks of showing the script to Castle Rock, Darabont had a $25 million budget to make his film (taking a $750,000 screenwriting and directing salary plus a percentage of the net profits), and pre-production began in January 1993.',

In [18]:
# Retrieve items from the collection

collection.get(
    ids = ['0','1']
)

{'ids': ['0', '1'],
 'embeddings': None,
 'documents': ['The Shawshank Redemption is a 1994 American prison drama film written and directed by Frank Darabont, based on the 1982 Stephen King novella Rita Hayworth and Shawshank Redemption. The film tells the story of banker Andy Dufresne (Tim Robbins), who is sentenced to life in Shawshank State Penitentiary for the murders of his wife and her lover, despite his claims of innocence. Over the following two decades, he befriends a fellow prisoner, contraband smuggler Ellis "Red" Redding (Morgan Freeman), and becomes instrumental in a money laundering operation led by the prison warden Samuel Norton (Bob Gunton). William Sadler, Clancy Brown, Gil Bellows, and James Whitmore appear in supporting roles.\nDarabont purchased the film rights to King\'s story in 1987, but development did not begin until five years later, when he wrote the script over an eight-week period. Two weeks after submitting his script to Castle Rock Entertainment, Darabont secured a $25 million budget to produce The Shawshank Redemption, which started pre-production in January 1993. While the film is set in Maine, principal photography took place from June to August 1993 almost entirely in Mansfield, Ohio, with the Ohio State Reformatory serving as the eponymous penitentiary. The project attracted many stars for the role of Andy, including Tom Hanks, Tom Cruise, and Kevin Costner. Thomas Newman provided the film\'s score.\nWhile The Shawshank Redemption received critical acclaim upon its release—particularly for its story, the performances of Robbins and Freeman, Newman\'s score, Darabont\'s direction and screenplay and Roger Deakins\' cinematography—the film was a box-office disappointment, earning only $16 million during its initial theatrical run. Many reasons were cited for its failure at the time, including competition from the films Pulp Fiction and Forrest Gump, the general unpopularity of prison films, its lack of female characters, and even the title, which was considered to be confusing for audiences. It went on to receive multiple award nominations, including seven Academy Award nominations, and a theatrical re-release that, combined with international takings, increased the film\'s box-office gross to $73.3 million.\nOver 320,000 VHS rental copies were shipped throughout the United States, and on the strength of its award nominations and word of mouth, it became one of the top video rentals of 1995. The broadcast rights were acquired following the purchase of Castle Rock by Turner Broadcasting System, and it was shown regularly on the TNT network starting in 1997, further increasing its popularity. Decades after its release, the film was still broadcast regularly, and is popular in several countries, with audience members and celebrities citing it as a source of inspiration or naming it a favorite in various surveys, leading to its recognition as one of the most "beloved" films ever made. In 2015, the United States Library of Congress selected the film for preservation in the National Film Registry, finding it "culturally, historically, or aesthetically significant".',
  'In early 1947, Portland, Maine, banker Andy Dufresne arrives at Shawshank State Prison to serve two consecutive life sentences for murdering his wife and her lover. He is befriended by Ellis "Red" Redding, a contraband smuggler serving a life sentence, who procures a rock hammer and a large poster of Rita Hayworth for Andy. Assigned to work in the prison laundry, Andy is frequently sexually assaulted by "the Sisters" and their leader, Bogs Diamond.\nIn 1949, Andy overhears the captain of the guards, Byron Hadley, complaining about being taxed on an inheritance and offers to help him shelter the money legally. After an assault by the Sisters nearly kills Andy, Hadley beats and cripples Bogs, who is subsequently transferred to another prison; Andy is not attacked again. Warden Samuel Norton meets Andy and reassigns him to the prison library to assist elderly inmate Brooks Hatlen, a front to use Andy\'s financial expertise to manage financial matters for other prison staff, guards from other prisons, and the warden himself. Andy begins writing weekly letters to the state legislature requesting funds to improve the prison\'s decrepit library.\nBrooks is paroled in 1954 after serving 50 years, but he cannot adjust to the outside world and eventually hangs himself. The legislature sends a library donation that includes a recording of The Marriage of Figaro; Andy plays an excerpt over the public address system and is punished with solitary confinement. After his release from solitary, Andy explains to a dismissive Red that hope is what gets him through his sentence. In 1963, Norton begins exploiting prison labor for public works, profiting by undercutting skilled labor costs and receiving bribes. Andy launders the money using the alias "Randall Stephens".\nIn 1965, Andy and Red befriend Tommy Williams, a young prisoner incarcerated for burglary. A year later, Andy helps him pass his General Educational Development (GED) exam. Tommy reveals to Red and Andy that his cellmate at another prison had claimed responsibility for the murders of which Andy was convicted. Andy brings the information to Norton who refuses to listen and, when Andy mentions the money laundering, sends Andy to solitary confinement and has Hadley fatally shoot Tommy under the guise of an escape attempt. Andy refuses to continue the money laundering, but Norton threatens to destroy the library, remove Andy\'s protection by the guards, and move him to worse conditions. Andy is released from solitary confinement after two months, and he tells a skeptical Red that he dreams of living in Zihuatanejo, a Mexican town on the Pacific coast. Andy also tells him of a specific hayfield near Buxton, asking Red to promise, once he is released, to retrieve a package that Andy buried there. Red worries about Andy\'s mental well-being, especially when he learns Andy asked a fellow inmate for some rope.\nAt the next day\'s roll call, the guards find Andy\'s cell empty. An irate Norton throws a rock at a poster of Raquel Welch hanging on the cell wall, revealing a tunnel that Andy had dug with his rock hammer over the past 19 years. The previous night, Andy used the rope to escape through the tunnel and prison sewage pipe, taking Norton\'s suit, shoes, and ledger, containing evidence of the money laundering. While guards search for him, Andy poses as Randall Stephens, withdraws over $370,000 of the laundered money from several banks, and mails the ledger and other evidence of the corruption and murders at Shawshank to a local newspaper. State police arrive at Shawshank and take Hadley into custody, while Norton commits suicide to avoid arrest.\nThe following year, Red is paroled after serving 40 years but struggles to adapt to life outside prison and fears that he never will. Remembering his promise to Andy, he visits Buxton and finds a cache containing money and a letter asking him to come to Zihuatanejo. Red violates his parole by traveling to Fort Hancock, Texas, and crossing the border into Mexico, admitting that he finally feels hope. He finds Andy sanding an old boat on a Zihuatanejo beach, and the two reunited friends happily embrace.'],
 'uris': None,
 'included': ['metadatas', 'documents'],
 'data': None,
 'metadatas': [None, None]}

In [36]:
# Add only the documents and ids into the collection, and ChromaDB will create embeddings on its own using the default embedding model - 'all-MiniLM-L6-v2'

temp_collection = chroma_client.get_or_create_collection(name="Temporary")
documents = ['Generative AI is an exciting space!', 'Generative AI encompasses all modalities including LLMs', 'Can Generative AI take my job?']
collection.add(
    documents = documents,
    ids = [str(i) for i in range(0, len(documents))],
)

In [20]:
# List all the collection created

chroma_client.list_collections()

[Collection(name=Semantic_Search_with_Chromadb), Collection(name=Temporary)]

In [21]:
# Delete a collection

chroma_client.delete_collection("Temporary")

### <font color = red> 2.2 Querying on ChromaDB </font>

* **`collection.query()`**

In [22]:
# Read the query from the user
query = input()

# Query the ChromaDB collection using `collection.query()
results = collection.query(
    query_texts=query,
    n_results=3,
    include = ['documents', 'distances']
)

 who all are the actors ?

In [23]:
# !pip install -U -q sentence-
# # Encode query using Sentence Transformer model
# from sentence_transformers import SentenceTransformer

# model_name = "all-MiniLM-L6-v2"
# embedder = SentenceTransformer(model_name)
# query_embedding = embedder.encode(query)

In [24]:
# See the results

results

{'ids': [['62', '84', '64']],
 'embeddings': None,
 'documents': [['Other actors playing smaller roles in the Sicilian sequence are Simonetta Stefanelli as Apollonia Vitelli-Corleone, Angelo Infanti as Fabrizio, Corrado Gaipa as Don Tommasino, Franco Citti as Calò and Saro Urzì as Vitelli.',
   'Once Robert De Niro agreed to play Jimmy Conway, Scorsese was able to secure the money needed to make the film. Ray Liotta, who played Henry Hill, had read Pileggi\'s book when it came out and was fascinated by it. A couple of years afterward, his agent told him Scorsese was going to direct a film adaptation. In 1988, Liotta met Scorsese over a period of a couple of months and auditioned for the film. He campaigned aggressively for a role, though Warner Bros. Pictures wanted a well-known actor; he later said, "I think they would\'ve rather had Eddie Murphy than me." Scorsese cast Liotta after De Niro saw him in Jonathan Demme\'s Something Wild (1986); Scorsese was surprised by "his explosive energy" in that film. Al Pacino and John Malkovich were considered for the role of Conway, and Sean Penn, Alec Baldwin, Val Kilmer, and Tom Cruise were considered for the role of Hill.To prepare for the role, De Niro consulted with Pileggi, who had research material that had been discarded while writing the book. De Niro often called Hill several times a day to ask how Burke walked, held his cigarette, and so on. Driving to and from the set, Liotta listened to FBI audio cassette tapes of Hill, so he could practice speaking like his real-life counterpart. Madonna was considered for the role of Karen Hill. To research her role, Lorraine Bracco tried to get close to a mob wife but was unable to, because they exist in a very tight-knit community. She decided not to meet the real Karen, saying she "thought it would be better if the creation came from me. I used her life with her parents as an emotional guideline for the role." Paul Sorvino had no problem finding the voice and walk of his character, but found it challenging finding what he called "that kernel of coldness and absolute hardness that is antithetical to my nature except when my family is threatened."Former EDNY prosecutor Edward A. McDonald appeared in the film as himself, re-creating the conversation he had with Henry and Karen Hill about joining the Witness Protection Program. McDonald, who was friends with Pileggi, was cast on a whim; while a location scout was taking pictures of his office, McDonald casually remarked that he would be happy to play himself if needed. Pileggi called him an hour later asking if he was serious, and he was cast. The scene was unscripted, with McDonald improvising the line referring to Karen as a "babe-in-the-woods."',
   'Evans wanted the picture to be directed by an Italian American to make the film "ethnic to the core". Paramount\'s latest mafia movie, The Brotherhood, had done very poorly at the box office; Evans believed that the reason for its failure was its almost complete lack of cast members or creative personnel of Italian descent (the director Martin Ritt and star Kirk Douglas were not Italian). Sergio Leone was Paramount\'s first choice to direct the film. Leone turned down the option, in order to work on his own gangster film Once Upon a Time in America. Peter Bogdanovich was then approached but he also declined the offer because he was not interested in the mafia. In addition, Peter Yates, Richard Brooks, Arthur Penn, Costa-Gavras, and Otto Preminger were all offered the position and declined. Evans\' chief assistant Peter Bart suggested Francis Ford Coppola, as a director of Italian ancestry who would work for a low sum and budget after the poor reception of his latest film The Rain People. Coppola initially turned down the job because he found Puzo\'s novel sleazy and sensationalist, describing it as "pretty cheap stuff". At the time Coppola\'s studio, American Zoetrope, owed over $400,000 to Warner Bros. for budget overruns with the film THX 1138 and when coupled with his poor financial standing, along with advice from friends and family, Coppola reversed his initial decision and took the job. Coppola was officially announced as director of the film on September 28, 1970.  Coppola agreed to receive $125,000 and six percent of the gross rentals. Coppola later found a deeper theme for the material and decided that the film should not be about organized crime but a family chronicle, a metaphor for capitalism in America.']],
 'uris': None,
 'included': ['documents', 'distances'],
 'data': None,
 'metadatas': None,
 'distances': [[1.1252909898757935, 1.2204152345657349, 1.2348597049713135]]}

In [25]:
# Format the results to return in a more structured and readable form

data = {'Document': results['documents'][0], 'Distance': results['distances'][0]}
results_df = pd.DataFrame.from_dict(data)
results_df

                                            Document  Distance
0  Other actors playing smaller roles in the Sici...  1.125291
1  Once Robert De Niro agreed to play Jimmy Conwa...  1.220415
2  Evans wanted the picture to be directed by an ...  1.234860

### 1.3 <font color = red> Updating Collections </font>

* **`collection.update()`**
* **`collection.upsert()`**

In [26]:
# Converting all text chunks to lowercase

section_chunk_embeddings['Chunk Text'] = section_chunk_embeddings['Chunk Text'].apply(lambda x: x.lower())

In [27]:
# Adding a metadata column containing the title of the page and the section name

section_chunk_embeddings['Metadata'] = section_chunk_embeddings.apply(lambda x: {'Title': x['Title'], 'Section': x["Section Title"]}, axis=1)

In [28]:
section_chunk_embeddings

,Title,Section Title,Chunk Text,Embeddings,Metadata
0,The Shawshank Redemption,Introduction,the shawshank redemption is a 1994 american pr...,"[-0.045234, -0.028654, -0.084308, 0.025436, -0...","{'Title': 'The Shawshank Redemption', 'Section..."
1,The Shawshank Redemption,Plot,"in early 1947, portland, maine, banker andy du...","[0.014254, 0.0067946, -0.037625, -0.016357, -0...","{'Title': 'The Shawshank Redemption', 'Section..."
2,The Shawshank Redemption,Cast,tim robbins as andy dufresne: a banker sentenc...,"[-0.053459, -0.053774, -0.12491, -0.012516, -0...","{'Title': 'The Shawshank Redemption', 'Section..."
3,The Shawshank Redemption,Analysis,the film has been interpreted as being grounde...,"[-0.055615, 0.051125, -0.083388, -0.0088534, -...","{'Title': 'The Shawshank Redemption', 'Section..."
4,The Shawshank Redemption,Development,darabont first collaborated with author stephe...,"[-0.033833, -0.034259, -0.022021, 0.083097, -0...","{'Title': 'The Shawshank Redemption', 'Section..."
...,...,...,...,...,...
90,Goodfellas,Box office,"goodfellas grossed $6.3 million from 1,070 the...","[0.028257, -0.062327, -0.015942, 0.078449, -0....","{'Title': 'Goodfellas', 'Section': 'Box office'}"
91,Goodfellas,Critical response,according to review aggregator rotten tomatoes...,"[-0.010413, -0.031451, -0.12268, 0.024364, 0.0...","{'Title': 'Goodfellas', 'Section': 'Critical r..."
92,Goodfellas,Lists,the film was ranked the best of 1990 by roger ...,"[-0.0047438, -0.095356, -0.063817, 0.019216, 0...","{'Title': 'Goodfellas', 'Section': 'Lists'}"
93,Goodfellas,Accolades,it became one of the eight films to win best p...,"[-0.0066345, -0.07772, -0.01668, 9.9736e-05, 0...","{'Title': 'Goodfellas', 'Section': 'Accolades'}"
94,Goodfellas,Legacy,goodfellas is no. 94 on the american film inst...,"[-0.0017614, -0.056696, -0.071819, 0.0085434, ...","{'Title': 'Goodfellas', 'Section': 'Legacy'}"

In [29]:
# Convert the metadata column to a list to feed it to ChromaDB

metadata_list = section_chunk_embeddings['Metadata'].tolist()

In [30]:
# Update the collection using `collection.upsert()`

collection.upsert(
    embeddings = section_chunk_embeddings['Embeddings'].to_list(),
    documents = section_chunk_embeddings['Chunk Text'].to_list(),
    metadatas = metadata_list,
    ids = [str(i) for i in range(0, len(section_chunk_embeddings['Embeddings']))],
)

In [31]:
collection.peek()

{'ids': ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'],
 'embeddings': array([[-0.045234 , -0.028654 , -0.084308 , ..., -0.013494 ,  0.0042968,
         -0.06522  ],
        [ 0.014254 ,  0.0067946, -0.037625 , ..., -0.0097042,  0.038454 ,
         -0.075619 ],
        [-0.053459 , -0.053774 , -0.12491  , ..., -0.019534 ,  0.059722 ,
         -0.062948 ],
        ...,
        [-0.033779 , -0.035569 ,  0.0085257, ...,  0.012246 , -0.026384 ,
          0.016961 ],
        [-0.068227 , -0.04472  , -0.06537  , ...,  0.067921 , -0.020769 ,
         -0.0386   ],
        [-0.022781 , -0.022584 , -0.095704 , ..., -0.10307  , -0.047831 ,
          0.043886 ]], shape=(10, 384)),
 'documents': ['the shawshank redemption is a 1994 american prison drama film written and directed by frank darabont, based on the 1982 stephen king novella rita hayworth and shawshank redemption. the film tells the story of banker andy dufresne (tim robbins), who is sentenced to life in shawshank state penitentiary for the murders of his wife and her lover, despite his claims of innocence. over the following two decades, he befriends a fellow prisoner, contraband smuggler ellis "red" redding (morgan freeman), and becomes instrumental in a money laundering operation led by the prison warden samuel norton (bob gunton). william sadler, clancy brown, gil bellows, and james whitmore appear in supporting roles.\ndarabont purchased the film rights to king\'s story in 1987, but development did not begin until five years later, when he wrote the script over an eight-week period. two weeks after submitting his script to castle rock entertainment, darabont secured a $25 million budget to produce the shawshank redemption, which started pre-production in january 1993. while the film is set in maine, principal photography took place from june to august 1993 almost entirely in mansfield, ohio, with the ohio state reformatory serving as the eponymous penitentiary. the project attracted many stars for the role of andy, including tom hanks, tom cruise, and kevin costner. thomas newman provided the film\'s score.\nwhile the shawshank redemption received critical acclaim upon its release—particularly for its story, the performances of robbins and freeman, newman\'s score, darabont\'s direction and screenplay and roger deakins\' cinematography—the film was a box-office disappointment, earning only $16 million during its initial theatrical run. many reasons were cited for its failure at the time, including competition from the films pulp fiction and forrest gump, the general unpopularity of prison films, its lack of female characters, and even the title, which was considered to be confusing for audiences. it went on to receive multiple award nominations, including seven academy award nominations, and a theatrical re-release that, combined with international takings, increased the film\'s box-office gross to $73.3 million.\nover 320,000 vhs rental copies were shipped throughout the united states, and on the strength of its award nominations and word of mouth, it became one of the top video rentals of 1995. the broadcast rights were acquired following the purchase of castle rock by turner broadcasting system, and it was shown regularly on the tnt network starting in 1997, further increasing its popularity. decades after its release, the film was still broadcast regularly, and is popular in several countries, with audience members and celebrities citing it as a source of inspiration or naming it a favorite in various surveys, leading to its recognition as one of the most "beloved" films ever made. in 2015, the united states library of congress selected the film for preservation in the national film registry, finding it "culturally, historically, or aesthetically significant".',
  'in early 1947, portland, maine, banker andy dufresne arrives at shawshank state prison to serve two consecutive life sentences for murdering his wife and her lover. he is befriended by ellis "red" redding, a contraband smuggler serving a life sentence, who procures a rock hammer and a large poster of rita hayworth for andy. assigned to work in the prison laundry, andy is frequently sexually assaulted by "the sisters" and their leader, bogs diamond.\nin 1949, andy overhears the captain of the guards, byron hadley, complaining about being taxed on an inheritance and offers to help him shelter the money legally. after an assault by the sisters nearly kills andy, hadley beats and cripples bogs, who is subsequently transferred to another prison; andy is not attacked again. warden samuel norton meets andy and reassigns him to the prison library to assist elderly inmate brooks hatlen, a front to use andy\'s financial expertise to manage financial matters for other prison staff, guards from other prisons, and the warden himself. andy begins writing weekly letters to the state legislature requesting funds to improve the prison\'s decrepit library.\nbrooks is paroled in 1954 after serving 50 years, but he cannot adjust to the outside world and eventually hangs himself. the legislature sends a library donation that includes a recording of the marriage of figaro; andy plays an excerpt over the public address system and is punished with solitary confinement. after his release from solitary, andy explains to a dismissive red that hope is what gets him through his sentence. in 1963, norton begins exploiting prison labor for public works, profiting by undercutting skilled labor costs and receiving bribes. andy launders the money using the alias "randall stephens".\nin 1965, andy and red befriend tommy williams, a young prisoner incarcerated for burglary. a year later, andy helps him pass his general educational development (ged) exam. tommy reveals to red and andy that his cellmate at another prison had claimed responsibility for the murders of which andy was convicted. andy brings the information to norton who refuses to listen and, when andy mentions the money laundering, sends andy to solitary confinement and has hadley fatally shoot tommy under the guise of an escape attempt. andy refuses to continue the money laundering, but norton threatens to destroy the library, remove andy\'s protection by the guards, and move him to worse conditions. andy is released from solitary confinement after two months, and he tells a skeptical red that he dreams of living in zihuatanejo, a mexican town on the pacific coast. andy also tells him of a specific hayfield near buxton, asking red to promise, once he is released, to retrieve a package that andy buried there. red worries about andy\'s mental well-being, especially when he learns andy asked a fellow inmate for some rope.\nat the next day\'s roll call, the guards find andy\'s cell empty. an irate norton throws a rock at a poster of raquel welch hanging on the cell wall, revealing a tunnel that andy had dug with his rock hammer over the past 19 years. the previous night, andy used the rope to escape through the tunnel and prison sewage pipe, taking norton\'s suit, shoes, and ledger, containing evidence of the money laundering. while guards search for him, andy poses as randall stephens, withdraws over $370,000 of the laundered money from several banks, and mails the ledger and other evidence of the corruption and murders at shawshank to a local newspaper. state police arrive at shawshank and take hadley into custody, while norton commits suicide to avoid arrest.\nthe following year, red is paroled after serving 40 years but struggles to adapt to life outside prison and fears that he never will. remembering his promise to andy, he visits buxton and finds a cache containing money and a letter asking him to come to zihuatanejo. red violates his parole by traveling to fort hancock, texas, and crossing the border into mexico, admitting that he finally feels hope. he finds andy sanding an old boat on a zihuatanejo beach, and the two reunited friends happily embrace.',
  'tim robbins as andy dufresne: a banker sentenced to life in prison in 1947 for the murder of his wife and her lover\nmorgan freeman as ellis boyd "red" redding: a prison contraband smuggler who befriends andy\nbob gunton as samuel norton: the pious and cruel warden of shawshank penitentiary\nwilliam sadler as heywood: a member of red\'s gang of long-serving convicts\nclancy brown as byron hadley: the brutal captain of the prison guards\ngil bellows as tommy williams: a young convict imprisoned for burglary in 1965\njames whitmore as brooks hatlen: the elderly prison librarian, imprisoned at shawshank for over five decadesthe cast also includes mark rolston as bogs diamond, the head of "the sisters" gang and a prison rapist; jeffrey demunn as the prosecuting attorney in dufresne\'s trial; alfonso freeman as fresh fish con; ned bellamy and don mcmanus as, respectively, prison guards youngblood and wiley; and dion anderson as head bull haig. renee blaine portrays andy\'s wife, and scott mann portrays her golf-instructor lover glenn quentin. frank medrano plays fat ass, one of andy\'s fellow new inmates who is beaten to death by hadley, and bill bolender plays elmo blatch, a convict who may actually be responsible for the crimes for which andy is convicted. james kisicki and claire slemmer portray the maine national bank manager and a teller, respectively.',
  'the film has been interpreted as being grounded in christian mysticism. andy is offered as a messianic, christ-like figure, with red describing him early in the film as having an aura that engulfs and protects him from shawshank. the scene in which andy and several inmates tar the prison roof can be seen as a recreation of the last supper, with andy obtaining beer/wine for the twelve inmates/disciples as freeman describes them as the "lords of all creation" invoking jesus\' blessing. director frank darabont responded that this was not his deliberate intention, but he wanted people to find their own meaning in the film. the discovery of the marriage of figaro record is described in the screenplay as akin to finding the holy grail, bringing the prisoners to a halt, and causing the sick to rise up in their beds.early in the film, warden norton quotes jesus christ to describe himself to andy, saying, "i am the light of the world", declaring himself andy\'s savior, but this description can also reference lucifer, the bearer of light. indeed, the warden does not enforce the general rule of law, but chooses to enforce his own rules and punishments as he sees fit, becoming a law unto himself, like the behavior of satan. the warden has also been compared to former united states president richard nixon. norton\'s appearance and public addresses can be seen to mirror nixon\'s. similarly, norton projects an image of a holy man, speaking down sanctimoniously to the servile masses while running corrupt scams, like those of which nixon was accused.\nzihuatanejo has been interpreted as an analog for heaven or paradise. in the film, andy describes it as a place with no memory, offering absolution from his sins by forgetting about them or allowing them to be washed away by the pacific ocean, whose name means "peaceful". the possibility of escaping to zihuatanejo is only raised after andy admits that he feels responsible for his wife\'s death. similarly, red\'s freedom is only earned once he accepts he cannot save himself or atone for his sins. freeman has described red\'s story as one of salvation as he is not innocent of his crimes, unlike andy who finds redemption. while some christian viewers interpret zihuatanejo as heaven, film critic mark kermode wrote that it can also be interpreted as a nietzschean form of guiltlessness achieved outside traditional notions of good and evil, where the amnesia offered is the destruction rather than forgiveness of sin, meaning andy\'s aim is secular and atheistic. just as andy can be interpreted as a christ-like figure, he can be seen as a zarathustra-like prophet offering escape through education and the experience of freedom. film critic roger ebert argued that the shawshank redemption is an allegory for maintaining one\'s feeling of self-worth when placed in a hopeless position. andy\'s integrity is an important theme in the story line, especially in prison, where integrity is lacking.robbins himself believes that the concept of zihuatanejo resonates with audiences because it represents a form of escape that can be achieved after surviving for many years within whatever "jail" someone finds themselves in, whether a bad relationship, job, or environment. robbins said that it is important that such a place exists for us. isaac m. morehouse suggests that the film provides a great illustration of how characters can be free, even in prison, or imprisoned, even in freedom, based on their outlooks on life. philosopher jean-paul sartre described freedom as an ongoing project that requires attention and resilience, without which a person begins to be defined by others or institutions, mirroring red\'s belief that inmates become dependent on the prison to define their lives. andy displays resilience through rebellion, by playing music over the prison loudspeaker, and refusing to continue with the money-laundering scam.many elements can be considered as tributes to the power of cinema. in the prison theater, the inmates watch the film gilda (1946), but this scene was originally intended to feature the lost weekend (1945). the interchangeability of the films used in the prison theater suggests that it is the cinematic experience and not the subject that is key to the scene, allowing the men to escape the reality of their situation. immediately following this scene, andy is assaulted by the sisters in the projector room and uses a film reel to help fight them off. at the end of the film, andy passes through a hole in his cell hidden by a movie poster to escape both his cell and ultimately shawshank.andy and red\'s relationship has been described as a nonsexual story between two men, that few other films offer, as the friendship is not built on conducting a caper, car chases, or developing a relationship with women. philosopher alexander hooke argued that andy and red\'s true freedom is their friendship, being able to share joy and humor with each other.',
  'darabont first collaborated with author stephen king in 1983 on the short film adaptation of "the woman in the room", buying the rights from him for $1—a dollar deal that king used to help new directors build a résumé by adapting his short stories. after receiving his first screenwriting credit in 1987 for a nightmare on elm street 3: dream warriors, darabont returned to king with $5,000 to purchase the rights to adapt rita hayworth and shawshank redemption, a 96-page novella from king\'s 1982 collection different seasons, written to explore genres other than the horror stories for which he was commonly known. although king did not understand how the story, largely focused on red contemplating his fellow prisoner andy, could be turned into a feature film, darabont believed it was "obvious". king never cashed the $5,000 check from darabont; he later framed it and returned it to darabont accompanied by a note which read: "in case you ever need bail money. love, steve."five years later, darabont wrote the script over an eight-week period. he expanded on elements of king\'s story. brooks, who in the novella is a minor character who dies in a retirement home, became a tragic character who eventually hanged himself. tommy, who in the novella trades his evidence exonerating andy for transfer to a nicer prison, in the screenplay is murdered on the orders of warden norton, who is a composite of several warden characters in king\'s story. darabont opted to create a single warden character to serve as the primary antagonist. among his inspirations, darabont listed the works of director frank capra, including mr. smith goes to washington (1939) and it\'s a wonderful life (1946), describing them as tall tales; darabont likened the shawshank redemption to a tall tale more than a prison movie. he also cited goodfellas (1990) as an inspiration on the use of dialogue to illustrate the passage of time in the script, and the prison drama birdman of alcatraz (1962) directed by john frankenheimer. while later scouting filming locations, darabont happened upon frankenheimer who was scouting for his own prison-set project against the wall. darabont recalled that frankenheimer took time out from his scouting to provide darabont with encouragement and advice.at the time, prison-based films were not considered likely box-office successes, but darabont\'s script was read by then-castle rock entertainment producer liz glotzer, whose interest in prison stories and reaction to the script, led her to threaten to quit if castle rock did not produce the shawshank redemption. director and castle rock co-founder rob reiner also liked the script. he offered darabont between $2.4 million and $3 million to allow him to direct it himself. reiner, who had previously adapted king\'s 1982 novella the body into the 1986 film stand by me, planned to cast tom cruise as andy and harrison ford as red.castle rock offered to finance any other film darabont wanted to develop. darabont seriously considered the offer, citing growing up poor in los angeles, believing it would elevate his standing in the industry, and that castle rock could have contractually fired him and given the film to reiner anyway, but he chose to remain the director, saying in a 2014 variety interview, "you can continue to defer your dreams in exchange for money and, you know, die without ever having done the thing you set out to do". reiner served as darabont\'s mentor on the project, instead. within two weeks of showing the script to castle rock, darabont had a $25 million budget to make his film (taking a $750,000 screenwriting and directing salary plus a percentage of the net profits), and pre-production began in january 1993.',

In [32]:
collection.get(
    ids = ['0','1']
)

{'ids': ['0', '1'],
 'embeddings': None,
 'documents': ['the shawshank redemption is a 1994 american prison drama film written and directed by frank darabont, based on the 1982 stephen king novella rita hayworth and shawshank redemption. the film tells the story of banker andy dufresne (tim robbins), who is sentenced to life in shawshank state penitentiary for the murders of his wife and her lover, despite his claims of innocence. over the following two decades, he befriends a fellow prisoner, contraband smuggler ellis "red" redding (morgan freeman), and becomes instrumental in a money laundering operation led by the prison warden samuel norton (bob gunton). william sadler, clancy brown, gil bellows, and james whitmore appear in supporting roles.\ndarabont purchased the film rights to king\'s story in 1987, but development did not begin until five years later, when he wrote the script over an eight-week period. two weeks after submitting his script to castle rock entertainment, darabont secured a $25 million budget to produce the shawshank redemption, which started pre-production in january 1993. while the film is set in maine, principal photography took place from june to august 1993 almost entirely in mansfield, ohio, with the ohio state reformatory serving as the eponymous penitentiary. the project attracted many stars for the role of andy, including tom hanks, tom cruise, and kevin costner. thomas newman provided the film\'s score.\nwhile the shawshank redemption received critical acclaim upon its release—particularly for its story, the performances of robbins and freeman, newman\'s score, darabont\'s direction and screenplay and roger deakins\' cinematography—the film was a box-office disappointment, earning only $16 million during its initial theatrical run. many reasons were cited for its failure at the time, including competition from the films pulp fiction and forrest gump, the general unpopularity of prison films, its lack of female characters, and even the title, which was considered to be confusing for audiences. it went on to receive multiple award nominations, including seven academy award nominations, and a theatrical re-release that, combined with international takings, increased the film\'s box-office gross to $73.3 million.\nover 320,000 vhs rental copies were shipped throughout the united states, and on the strength of its award nominations and word of mouth, it became one of the top video rentals of 1995. the broadcast rights were acquired following the purchase of castle rock by turner broadcasting system, and it was shown regularly on the tnt network starting in 1997, further increasing its popularity. decades after its release, the film was still broadcast regularly, and is popular in several countries, with audience members and celebrities citing it as a source of inspiration or naming it a favorite in various surveys, leading to its recognition as one of the most "beloved" films ever made. in 2015, the united states library of congress selected the film for preservation in the national film registry, finding it "culturally, historically, or aesthetically significant".',
  'in early 1947, portland, maine, banker andy dufresne arrives at shawshank state prison to serve two consecutive life sentences for murdering his wife and her lover. he is befriended by ellis "red" redding, a contraband smuggler serving a life sentence, who procures a rock hammer and a large poster of rita hayworth for andy. assigned to work in the prison laundry, andy is frequently sexually assaulted by "the sisters" and their leader, bogs diamond.\nin 1949, andy overhears the captain of the guards, byron hadley, complaining about being taxed on an inheritance and offers to help him shelter the money legally. after an assault by the sisters nearly kills andy, hadley beats and cripples bogs, who is subsequently transferred to another prison; andy is not attacked again. warden samuel norton meets andy and reassigns him to the prison library to assist elderly inmate brooks hatlen, a front to use andy\'s financial expertise to manage financial matters for other prison staff, guards from other prisons, and the warden himself. andy begins writing weekly letters to the state legislature requesting funds to improve the prison\'s decrepit library.\nbrooks is paroled in 1954 after serving 50 years, but he cannot adjust to the outside world and eventually hangs himself. the legislature sends a library donation that includes a recording of the marriage of figaro; andy plays an excerpt over the public address system and is punished with solitary confinement. after his release from solitary, andy explains to a dismissive red that hope is what gets him through his sentence. in 1963, norton begins exploiting prison labor for public works, profiting by undercutting skilled labor costs and receiving bribes. andy launders the money using the alias "randall stephens".\nin 1965, andy and red befriend tommy williams, a young prisoner incarcerated for burglary. a year later, andy helps him pass his general educational development (ged) exam. tommy reveals to red and andy that his cellmate at another prison had claimed responsibility for the murders of which andy was convicted. andy brings the information to norton who refuses to listen and, when andy mentions the money laundering, sends andy to solitary confinement and has hadley fatally shoot tommy under the guise of an escape attempt. andy refuses to continue the money laundering, but norton threatens to destroy the library, remove andy\'s protection by the guards, and move him to worse conditions. andy is released from solitary confinement after two months, and he tells a skeptical red that he dreams of living in zihuatanejo, a mexican town on the pacific coast. andy also tells him of a specific hayfield near buxton, asking red to promise, once he is released, to retrieve a package that andy buried there. red worries about andy\'s mental well-being, especially when he learns andy asked a fellow inmate for some rope.\nat the next day\'s roll call, the guards find andy\'s cell empty. an irate norton throws a rock at a poster of raquel welch hanging on the cell wall, revealing a tunnel that andy had dug with his rock hammer over the past 19 years. the previous night, andy used the rope to escape through the tunnel and prison sewage pipe, taking norton\'s suit, shoes, and ledger, containing evidence of the money laundering. while guards search for him, andy poses as randall stephens, withdraws over $370,000 of the laundered money from several banks, and mails the ledger and other evidence of the corruption and murders at shawshank to a local newspaper. state police arrive at shawshank and take hadley into custody, while norton commits suicide to avoid arrest.\nthe following year, red is paroled after serving 40 years but struggles to adapt to life outside prison and fears that he never will. remembering his promise to andy, he visits buxton and finds a cache containing money and a letter asking him to come to zihuatanejo. red violates his parole by traveling to fort hancock, texas, and crossing the border into mexico, admitting that he finally feels hope. he finds andy sanding an old boat on a zihuatanejo beach, and the two reunited friends happily embrace.'],
 'uris': None,
 'included': ['metadatas', 'documents'],
 'data': None,
 'metadatas': [{'Title': 'The Shawshank Redemption',
   'Section': 'Introduction'},
  {'Section': 'Plot', 'Title': 'The Shawshank Redemption'}]}

In [33]:
# Query on the collection again, this time with filters on the chunk texts and the metadata

query = input()

results = collection.query(
    query_texts=query,
    n_results=3,
    where = {'Section': 'Critical response'},
    where_document = {"$contains": "positive"},
    include = ['documents', 'distances']
)

 who all are the actors

In [34]:
results

{'ids': [['11', '91', '31']],
 'embeddings': None,
 'documents': [['the shawshank redemption opened to generally positive reviews. some reviewers compared the film to other well-received prison dramas, including birdman of alcatraz, cool hand luke, and riot in cell block 11. gene siskel said that, like one flew over the cuckoo\'s nest, the shawshank redemption is an inspirational drama about overcoming overbearing authority. audiences polled by cinemascore gave the film an average grade of "a" on an a+ to f scale.entertainment weekly\'s owen gleiberman said that freeman makes the red character feel genuine and "lived-in". janet maslin of the new york times said that freeman was quietly impressive, but lamented that red\'s role in the film had limited range, restricted to observing andy. she considered freeman\'s commanding performance made him a much stronger figure than simply an observer. maslin said that freeman\'s performance was especially moving when describing how dependent red had become on living within the prison walls. variety\'s leonard klady suggested that freeman had the "showier" role, allowing him "a grace and dignity that came naturally", without ever becoming banal, and the washington post\'s desson howe called freeman a "master" of comedic and poignant cadence. even kenneth turan\'s los angeles times review, which glotzer credited with derailing the film\'s box-office success, praised freeman, saying his "effortless screen presence lends shawshank the closest thing to credibility it can manage".of robbins\' performance, gleiberman said that in his "laconic-good-guy, neo-gary cooper role, [robbins] is unable to make andy connect with the audience". conversely, maslin said that andy has the more subdued role, but that robbins portrays him intensely, and effectively depicts the character as he transitions from new prisoner to aged father figure, and klady stated that his "riveting, unfussy ... precise, honest, and seamless" performance anchors the film. howe said that while the character is "cheesily messianic" for easily charming everyone to his side, comparing him to "forrest gump goes to jail", robbins exudes the perfect kind of innocence to sell the story. the hollywood reporter stated that both freeman and robbins gave outstanding, layered performances that imbued their characters with individuality, and rolling stone\'s peter travers said that the pair created something "undeniably powerful and moving". gunton and brown were deemed by klady as "extremely credible in their villainy", while howe countered that gunton\'s warden was a clichéd character who extols religious virtues while having people murdered.maslin called the film an impressive directorial debut that tells a gentle tale with a surprising amount of loving care, while klady said the only failings came when darabont focused for too long on supporting characters, or embellished a secondary story. the hollywood reporter said that both the directing and writing were crisp, while criticizing the film\'s long running time. klady said that the length and tone, while tempered by humor and unexpected events, would dampen the film\'s mainstream appeal, but the story offered a fascinating portrait of the innate humanity of the inmates. gleiberman disliked that the prisoners\' crimes were overlooked to portray them more as good guys. turan similarly objected to what he perceived as extreme violence and rape scenes, and making most of the prisoners seem like a "bunch of swell and softhearted guys" to cast the prison experience in a "rosy glow". klady summarized the film as "estimable and haunting entertainment", comparing it to a rough diamond with small flaws, but howe criticized it for deviating with multiple subplots, and pandering by choosing to resolve the story with andy and red\'s reunion, rather than leaving the mystery. ebert noted that the story works because it is not about andy as the hero, but how red perceives him.deakins\' cinematography was roundly praised, with the hollywood reporter calling it "foreboding" and "well-crafted", and travers saying "the everyday agonies of prison life are meticulously laid out ... you can almost feel the frustration and rage seeping into the skin of the inmates". gleiberman praised the choice of scenery, writing "the moss-dark, saturated images have a redolent sensuality; you feel as if you could reach out and touch the prison walls". the hollywood reporter said of newman\'s score, "at its best moments, alights with radiant textures and sprightly grace notes, nicely emblematic of the film\'s central theme", and klady described it as "the right balance between the somber and the absurd".',
   'according to review aggregator rotten tomatoes, 96% of 107 critics have given the film a positive review, with an average rating of 9.00/10. the website\'s critics consensus reads, "hard-hitting and stylish, goodfellas is a gangster classic—and arguably the high point of martin scorsese\'s career." metacritic has assigned the film a weighted average score of 92 out of 100 based on reviews from 21 critics, indicating "universal acclaim". audiences polled by cinemascore gave the film an average grade of "a−" on an a+ to f scale.in his review for the chicago sun-times, roger ebert gave the film a full four stars and wrote, "no finer film has ever been made about organized crime – not even the godfather." in his review for the chicago tribune, gene siskel wrote, "all of the performances are first-rate; pesci stands out, though, with his seemingly unscripted manner. goodfellas is easily one of the year\'s best films." both named it as the best film of 1990. in his review for the new york times, vincent canby wrote, "more than any earlier scorsese film, goodfellas is memorable for the ensemble nature of the performances... the movie has been beautifully cast from the leading roles to the bits. there is flash also in some of mr. scorsese\'s directorial choices, including freeze frames, fast cutting and the occasional long tracking shot. none of it is superfluous." usa today gave the film four out of four stars and called it, "great cinema—and also a whopping good time." david ansen, in his review for newsweek magazine, wrote "every crisp minute of this long, teeming movie vibrates with outlaw energy." rex reed said, "big, rich, powerful and explosive. one of scorsese\'s best films! goodfellas is great entertainment." in his review for time, richard corliss wrote, "so it is scorsese\'s triumph that goodfellas offers the fastest, sharpest 2½-hr. ride in recent film history."',
   'the dark knight received critical acclaim. on rotten tomatoes, the film holds a 94% approval rating from the aggregated reviews of 345 critics, with an average score of 8.6/10. the consensus reads; "dark, complex and unforgettable, the dark knight succeeds not just as an entertaining comic book film, but as a richly thrilling crime saga." on metacritic the film has a weighted average score of 84 out of 100 based on 39 critics, indicating "universal acclaim". audiences polled by cinemascore gave the film an average grade of "a" on an a+ to f scale.several publications called the dark knight the best comic-book hero adaptation ever made. roger ebert said it, alongside iron man, had redefined the potential of superhero films by combining comic-book tropes with real world events. some appreciated its complex moral tale about the effects of vigilantism and terrorism on contemporary society. emanuel levy and manohla dargis praised the depiction of the characters as possessing both positive and negative aspects, such as the batman\'s efforts to end crime provoking unintended consequences and a greater response from criminals; dargis believed the dark knight\'s exploration of chaos, fear, and death, following the september 11 attacks in 2001, represented "that american movies have entered a new era of ambivalence when it comes to their heroes or maybe just superness." others criticized the dark, grim, intense, and self-serious tone as lacking any elements of fun or fantasy. david denby said the dark knight was a product of a "time of terror", but focused on embracing and unleashing it while cynically setting up a sequel. stephanie zacharek and david edelstein criticized a perceived lack of visual storytelling in favor of exposition, and aspects of the plot being difficult to follow amid the fast pace and loud score. christopher\'s action direction was criticized, especially during fight scenes where it could be difficult to see things clearly, although the prologue bank heist was praised as among the film\'s best.ledger\'s performance received near-unanimous praise with the caveat that his death made the role both highly anticipated and difficult to watch. dargis, among others, described ledger as realizing the joker so convincingly, intensely, and viscerally it made the audience forget about the actor behind the makeup. the village voice wrote the performance would have made ledger a legend even if he had lived. other reviews said ledger outshone nicholson\'s "magnificent" performance with macabre humor and malevolence. reviews generally agreed the joker was the best-written character, and that ledger commanded scenes from the entire cast to create one of the most mesmerizing cinematic villains. zacharek, however, lamented that the performance was not in service of a better film.bale\'s reception was mixed; his performance was considered to be alternately "captivating" or serviceable, but ultimately uninteresting and undermined by portraying an immovable and generally unchanged character who delivers the batman\'s dialogue in a hoarse, unvarying tone. eckhart\'s performance was generally well received; reviewers praised his portrayal of dent as charismatic, and the character\'s subsequent transformation into a sad, bitter "monster", although variety considered his subplot the film\'s weakest. stephen hunter said the dent character was underwritten and that eckhart was incapable of portraying the role as intended. several reviewers regarded gyllenhaal as an improvement over holmes, although others said they found difficulty caring about the character and that gyllenhaal, while more talented than her predecessor, was miscast. peter travers praised oldman\'s skill in making a virtuous character interesting and he, among others, described caine\'s and freeman\'s performances as "effortless". ebert surmised the entire cast provided "powerful" performances that engage the audience, such that "we\'re surprised how deeply the drama affects us".']],
 'uris': None,
 'included': ['documents', 'distances'],
 'data': None,
 'metadatas': None,
 'distances': [[1.6366636753082275, 1.6468288898468018, 1.88066828250885]]}

In [35]:
data = {'Column1': results['documents'][0], 'Column2': results['distances'][0]}
results_df = pd.DataFrame.from_dict(data)
results_df

                                             Column1   Column2
0  the shawshank redemption opened to generally p...  1.636664
1  according to review aggregator rotten tomatoes...  1.646829
2  the dark knight received critical acclaim. on ...  1.880668